CONFIG= \
    __DEFAULT_PORT=6633 \
    __CLI_PORT=8000 \
    \
    __MAX_COMPONENTS=20 \
    __MAX_EVENTS=80 \
    __MAX_EVENT_CHAINS=10 \
    \
    __MAX_APPLICATIONS=10 \
    __MAX_APP_EVENTS=40 \
    __MAX_APP_EVENT_CHAINS=10 \
    \
    __MAX_META_EVENTS=10 \
    \
    __MAX_POLICIES=10 \
    __MAX_POLICY_ENTRIES=10 \
    \
    __NUM_THREADS=8 \
    \
    __MAX_NUM_SWITCHES=128 \
    __MAX_NUM_PORTS=64 \
