version: '3'

services:
  backend:
    image: mariadb:latest
    restart: unless-stopped
    command: --init-file /schemes/barista.sql
    volumes:
      - ../schemes/barista.sql:/schemes/barista.sql
    network_mode: host
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=barista

  barista:
    image: sdx4u/barista-base
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ../bin:/barista/bin
      - ./scripts/barista.sh:/barista/barista.sh
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    network_mode: host
    environment:
      - API_monitor=$API_monitor
      - CBENCH=$CBENCH
    entrypoint: ["/barista/barista.sh"]

  l2-learning:
    image: sdx4u/barista-base
    restart: unless-stopped
    depends_on:
      - barista
    volumes:
      - ../bin:/barista/bin
      - ./scripts/l2_learning.sh:/barista/l2_learning.sh
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    network_mode: host
    environment:
      - CBENCH=$CBENCH
    entrypoint: ["/barista/l2_learning.sh"]

  rbac:
    image: sdx4u/barista-base
    restart: unless-stopped
    depends_on:
      - barista
    volumes:
      - ../bin:/barista/bin
      - ./scripts/rbac.sh:/barista/rbac.sh
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    network_mode: host
    entrypoint: ["/barista/rbac.sh"]
