Barista: app_events/include/app_event_msg_pack.h File Reference
app_event_msg_pack.h File Reference
#include "app_event_json.h"
Functions
static int activate_external_application (char *in_str)
Function to activate an external application.
static int deactivate_external_application (app_t *c)
Function to deactivate an external application.
static int av_push_ext_msg (app_t *c, uint32_t id, uint16_t type, uint16_t size, const void *input)
Function to send events to an external application.
static int av_send_ext_msg (app_t *c, uint32_t id, uint16_t type, uint16_t size, const void *input, void *output)
Function to send events to an external application and receive responses from it.
static void * reply_app_events (void *null)
Function to process requests from external applications and reply outputs.
static void * reply_proxy (void *null)
Function to connect worker threads to application threads via a queue proxy.
static int process_app_events (msg_t *msg)
Function to process app events.
static void * receive_app_events (void *null)
Function to receive app events from external applications.
static void * deliver_app_events (void *null)
Function to get app events from an app event queue.
int destroy_av_workers (ctx_t *ctx)
Function to destroy an app event queue.
Detailed Description
Author
Jaehyun Nam namjh.nosp@m.@kai.nosp@m.st.ac.nosp@m..kr
Definition in file app_event_msg_pack.h.
Function Documentation
activate_external_application()
static int activate_external_application (char * in_str) static
Parameters
in_str Handshake message
Definition at line 20 of file app_event_msg_pack.h.
 {
     json_t *json = NULL;
     json_error_t error;
     json = json_loads(in_str, 0, &error);
     if (!json) {
         PERROR("json_loads");
         return -1;
     }
     uint32_t id = 0;
     json_t *j_id = json_object_get(json, "id");
     if (json_is_integer(j_id))
         id = json_integer_value(j_id);
     char name[__CONF_WORD_LEN] = {0};
     json_t *j_name = json_object_get(json, "name");
     if (json_is_string(j_name))
         strcpy(name, json_string_value(j_name));
     if (id == 0 || strlen(name) == 0) {
         json_decref(json);
         return -1;
     }
     int i;
     for (i=0; i<av_ctx->num_apps; i++) {
         if (av_ctx->app_list[i]->app_id == id) {
             if (strcmp(av_ctx->app_list[i]->name, name) == 0) {
                 av_ctx->app_list[i]->activated = TRUE;
                 json_decref(json);
                 return 0;
             } else {
                 json_decref(json);
                 return -1;
             }
         }
     }
     json_decref(json);
     return -1;
 }
av_push_ext_msg()
static int av_push_ext_msg (app_t * c, uint32_t id, uint16_t type, uint16_t size, const void * input) static
Parameters
c Application context
id Application ID
type Application event type
size The size of the given data
input The pointer of the given data
Definition at line 86 of file app_event_msg_pack.h.
References __MAX_EXT_MSG_SIZE, _app_t::activated, deactivate_external_application(), export_to_json(), _app_t::pull_addr, and _app_t::push_ctx.
 {
     if (!c->activated) return -1;
     char out_str[__MAX_EXT_MSG_SIZE];
     export_to_json(id, type, input, out_str);
     zmq_msg_t msg;
     zmq_msg_init_size(&msg, strlen(out_str));
     memcpy(zmq_msg_data(&msg), out_str, strlen(out_str));
     void *sock = zmq_socket(c->push_ctx, ZMQ_PUSH);
     if (zmq_connect(sock, c->pull_addr)) {
         zmq_msg_close(&msg);
         deactivate_external_application(c);
         return -1;
     } else {
         if (zmq_msg_send(&msg, sock, 0) < 0) {
             zmq_close(sock);
             zmq_msg_close(&msg);
             deactivate_external_application(c);
             return -1;
         }
         zmq_close(sock);
         zmq_msg_close(&msg);
     }
     return 0;
 }
av_send_ext_msg()
static int av_send_ext_msg (app_t * c, uint32_t id, uint16_t type, uint16_t size, const void * input, void * output) static
Parameters
c Application context
id Application ID
type Application event type
size The size of the given data
input The pointer of the given data
output The pointer to store the updated data
Returns
The return value received from the application
Definition at line 131 of file app_event_msg_pack.h.
References __MAX_EXT_MSG_SIZE, _app_t::activated, deactivate_external_application(), export_to_json(), import_from_json(), _app_t::reply_addr, and _app_t::req_ctx.
 {
     if (!c->activated) return -1;
     char out_str[__MAX_EXT_MSG_SIZE];
     export_to_json(id, type, input, out_str);
     zmq_msg_t out_msg;
     zmq_msg_init_size(&out_msg, strlen(out_str));
     memcpy(zmq_msg_data(&out_msg), out_str, strlen(out_str));
     void *sock = zmq_socket(c->req_ctx, ZMQ_REQ);
     if (zmq_connect(sock, c->reply_addr)) {
         zmq_msg_close(&out_msg);
         deactivate_external_application(c);
         return -1;
     } else {
         if (zmq_msg_send(&out_msg, sock, 0) < 0) {
             zmq_close(sock);
             zmq_msg_close(&out_msg);
             deactivate_external_application(c);
             return -1;
         } else {
             zmq_msg_close(&out_msg);
             zmq_msg_t in_msg;
             zmq_msg_init(&in_msg);
             int zmq_ret = zmq_msg_recv(&in_msg, sock, 0);
             if (zmq_ret < 0) {
                 zmq_close(sock);
                 zmq_msg_close(&in_msg);
                 deactivate_external_application(c);
                 return -1;
             } else {
                 char *in_str = zmq_msg_data(&in_msg);
                 in_str[zmq_ret] = '\0';
                 int ret = import_from_json(&id, &type, in_str, output);
                 zmq_close(sock);
                 zmq_msg_close(&in_msg);
                 return ret;
             }
         }
     }
 }
deactivate_external_application()
static int deactivate_external_application (app_t * c) static
Parameters
c Application context
Definition at line 69 of file app_event_msg_pack.h.
References _app_t::activated.
Referenced by av_push_ext_msg(), and av_send_ext_msg().
 {
     c->activated = FALSE;
     return 0;
 }
deliver_app_events()
static void* deliver_app_events (void * null) static
Parameters
null NULL
Definition at line 391 of file app_event_msg_pack.h.
 {
     void *recv = zmq_socket(av_pull_out_ctx, ZMQ_PULL);
     zmq_connect(recv, "inproc://av_pull_workers");
     while (av_ctx->av_on) {
         zmq_msg_t in_msg;
         zmq_msg_init(&in_msg);
         int zmq_ret = zmq_msg_recv(&in_msg, recv, 0);
         if (!av_ctx->av_on) {
             zmq_msg_close(&in_msg);
             break;
         } else if (zmq_ret == -1) {
             zmq_msg_close(&in_msg);
             continue;
         }
         char *in_str = zmq_msg_data(&in_msg);
         in_str[zmq_ret] = '\0';
         msg_t msg = {0};
         import_from_json(&msg.id, &msg.type, in_str, msg.data);
         zmq_msg_close(&in_msg);
         if (msg.id == 0) continue;
         else if (msg.type > AV_NUM_EVENTS) continue;
         process_app_events(&msg);
     }
     zmq_close(recv);
     return NULL;
 }
destroy_av_workers()
int destroy_av_workers (ctx_t * ctx)
Parameters
ctx The context of the Barista NOS
Definition at line 434 of file app_event_msg_pack.h.
 {
     ctx->av_on = FALSE;
     waitsec(1, 0);
     zmq_close(av_pull_in_sock);
     zmq_close(av_pull_out_sock);
     zmq_close(av_rep_app);
     zmq_close(av_rep_work);
     zmq_ctx_destroy(av_pull_in_ctx);
     zmq_ctx_destroy(av_pull_out_ctx);
     zmq_ctx_destroy(av_rep_ctx);
     return 0;
 }
process_app_events()
static int process_app_events (msg_t * msg) static
Parameters
msg Application events
Definition at line 292 of file app_event_msg_pack.h.
References _msg_t::data, flow_av_raise(), _msg_t::id, log_av_raise(), pktin_av_raise(), pktout_av_raise(), port_av_raise(), and _msg_t::type.
 {
     switch (msg->type) {
     // upstream events
     case AV_DP_RECEIVE_PACKET:
         pktin_av_raise(msg->id, AV_DP_RECEIVE_PACKET, sizeof(pktin_t), (const pktin_t *)msg->data);
         break;
     case AV_DP_FLOW_EXPIRED:
         flow_av_raise(msg->id, AV_DP_FLOW_EXPIRED, sizeof(flow_t), (const flow_t *)msg->data);
         break;
     case AV_DP_FLOW_DELETED:
         flow_av_raise(msg->id, AV_DP_FLOW_DELETED, sizeof(flow_t), (const flow_t *)msg->data);
         break;
     case AV_DP_PORT_ADDED:
         port_av_raise(msg->id, AV_DP_PORT_ADDED, sizeof(port_t), (const port_t *)msg->data);
         break;
     case AV_DP_PORT_MODIFIED:
         port_av_raise(msg->id, AV_DP_PORT_MODIFIED, sizeof(port_t), (const port_t *)msg->data);
         break;
     case AV_DP_PORT_DELETED:
         port_av_raise(msg->id, AV_DP_PORT_DELETED, sizeof(port_t), (const port_t *)msg->data);
         break;
     // downstream events
     case AV_DP_SEND_PACKET:
         pktout_av_raise(msg->id, AV_DP_SEND_PACKET, sizeof(pktout_t), (const pktout_t *)msg->data);
         break;
     case AV_DP_INSERT_FLOW:
         flow_av_raise(msg->id, AV_DP_INSERT_FLOW, sizeof(flow_t), (const flow_t *)msg->data);
         break;
     case AV_DP_MODIFY_FLOW:
         flow_av_raise(msg->id, AV_DP_MODIFY_FLOW, sizeof(flow_t), (const flow_t *)msg->data);
         break;
     case AV_DP_DELETE_FLOW:
         flow_av_raise(msg->id, AV_DP_DELETE_FLOW, sizeof(flow_t), (const flow_t *)msg->data);
         break;
     // log events
     case AV_LOG_DEBUG:
         log_av_raise(msg->id, AV_LOG_DEBUG, strlen((const char *)msg->data), (const char *)msg->data);
         break;
     case AV_LOG_INFO:
         log_av_raise(msg->id, AV_LOG_INFO, strlen((const char *)msg->data), (const char *)msg->data);
         break;
     case AV_LOG_WARN:
         log_av_raise(msg->id, AV_LOG_WARN, strlen((const char *)msg->data), (const char *)msg->data);
         break;
     case AV_LOG_ERROR:
         log_av_raise(msg->id, AV_LOG_ERROR, strlen((const char *)msg->data), (const char *)msg->data);
         break;
     case AV_LOG_FATAL:
         log_av_raise(msg->id, AV_LOG_FATAL, strlen((const char *)msg->data), (const char *)msg->data);
         break;
     default:
         break;
     }
     return 0;
 }
receive_app_events()
static void* receive_app_events (void * null) static
Parameters
null NULL
Definition at line 361 of file app_event_msg_pack.h.
References av_ctx, _ctx_t::av_on, and av_pull_in_sock.
 {
     while (av_ctx->av_on) {
         zmq_msg_t in_msg;
         zmq_msg_init(&in_msg);
         int zmq_ret = zmq_msg_recv(&in_msg, av_pull_in_sock, 0);
         if (!av_ctx->av_on) {
             zmq_msg_close(&in_msg);
             break;
         } else if (zmq_ret == -1) {
             zmq_msg_close(&in_msg);
             continue;
         }
         char *in_str = zmq_msg_data(&in_msg);
         in_str[zmq_ret] = '\0';
         zmq_msg_send(&in_msg, av_pull_out_sock, 0);
         zmq_msg_close(&in_msg);
     }
     return NULL;
 }
reply_app_events()
static void* reply_app_events (void * null) static
Parameters
null NULL
Definition at line 192 of file app_event_msg_pack.h.
 {
     void *recv = zmq_socket(av_rep_ctx, ZMQ_REP);
     zmq_connect(recv, "inproc://av_reply_workers");
     while (av_ctx->av_on) {
         zmq_msg_t in_msg;
         zmq_msg_init(&in_msg);
         int zmq_ret = zmq_msg_recv(&in_msg, recv, 0);
         if (!av_ctx->av_on) {
             zmq_msg_close(&in_msg);
             break;
         } else if (zmq_ret == -1) {
             zmq_msg_close(&in_msg);
             continue;
         }
         char *in_str = zmq_msg_data(&in_msg);
         in_str[zmq_ret] = '\0';
         // handshake with external app
         if (in_str[0] == '#') {
             if (activate_external_application(in_str+1) == 0) {
                 char out_str[] = "#{\"return\": 0}";
                 zmq_msg_t out_msg;
                 zmq_msg_init_size(&out_msg, strlen(out_str));
                 memcpy(zmq_msg_data(&out_msg), out_str, strlen(out_str));
                 zmq_msg_send(&out_msg, recv, 0);
                 zmq_msg_close(&out_msg);
             } else {
                 char out_str[] = "#{\"return\": -1}";
                 zmq_msg_t out_msg;
                 zmq_msg_init_size(&out_msg, strlen(out_str));
                 memcpy(zmq_msg_data(&out_msg), out_str, strlen(out_str));
                 zmq_msg_send(&out_msg, recv, 0);
                 zmq_msg_close(&out_msg);
             }
             zmq_msg_close(&in_msg);
             continue;
         }
         msg_t msg = {0};
         import_from_json(&msg.id, &msg.type, in_str, msg.data);
         zmq_msg_close(&in_msg);
         if (msg.id == 0) continue;
         else if (msg.type > AV_NUM_EVENTS) continue;
         int ret = 0;
         switch (msg.type) {
         // request-response events
         default:
             break;
         }
         msg.ret = ret;
         char out_str[__MAX_EXT_MSG_SIZE];
         export_to_json(msg.id, msg.type, msg.data, out_str);
         zmq_msg_t out_msg;
         zmq_msg_init_size(&out_msg, strlen(out_str));
         memcpy(zmq_msg_data(&out_msg), out_str, strlen(out_str));
         zmq_msg_send(&out_msg, recv, 0);
         zmq_msg_close(&out_msg);
         if (!av_ctx->av_on) break;
     }
     zmq_close(recv);
     return NULL;
 }
reply_proxy()
static void* reply_proxy (void * null) static
Parameters
null NULL
Definition at line 279 of file app_event_msg_pack.h.
 {
     zmq_proxy(av_rep_app, av_rep_work, NULL);
     return NULL;
 }