Barista: ext_apps/shim/include/app_event_zmq_pack.h File Reference
app_event_zmq_pack.h File Reference
#include <zmq.h>
#include "base64.h"
Functions
static int av_push_ext_msg (app_t *c, uint32_t id, uint16_t type, uint16_t size, const void *data)
Function to send events to an application.
static int av_send_ext_msg (app_t *c, uint32_t id, uint16_t type, uint16_t size, const void *data, app_event_out_t *out)
Function to send events to an application and receive responses from it.
static void * reply_app_events (void *null)
Function to process requests from applications.
static void * reply_proxy (void *null)
Function to connect work threads to application threads via a queue proxy.
static void * receive_app_events (void *null)
Function to receive app events from external applications.
int destroy_av_workers (ctx_t *ctx)
Function to destroy an app event queue.
Detailed Description
Author
Jaehyun Nam namjh.nosp@m.@kai.nosp@m.st.ac.nosp@m..kr
Definition in file app_event_zmq_pack.h.
Function Documentation
av_push_ext_msg()
static int av_push_ext_msg (app_t * c, uint32_t id, uint16_t type, uint16_t size, const void * data) static
Parameters
c Application context
id Application ID
type Application event type
size The size of the given data
data The pointer of the given data
Returns
None
Definition at line 24 of file app_event_zmq_pack.h.
References base64_encode(), _msg_t::data, FREE, _msg_t::id, _app_t::push_sock, size, and _msg_t::type.
 {
     msg_t msg = {0};
     msg.id = id;
     msg.type = type;
     memmove(msg.data, data, size);
     char *str = base64_encode((char *)&msg, sizeof(msg_t));
     zmq_send(c->push_sock, str, strlen(str), 0);
     FREE(str);
     return 0;
 }
av_send_ext_msg()
static int av_send_ext_msg (app_t * c, uint32_t id, uint16_t type, uint16_t size, const void * data, app_event_out_t * out) static
Parameters
c Application context
id Application ID
type Application event type
size The size of the given data
data The pointer of the given data
out The pointer to store the updated data
Returns
The return value received from an application
Definition at line 48 of file app_event_zmq_pack.h.
References __MAX_ZMQ_MSG_SIZE, base64_decode(), base64_encode(), _app_event_out_t::data, _msg_t::data, FREE, _msg_t::id, _app_t::req_sock, _msg_t::ret, size, and _msg_t::type.
 {
     int ret = 0;
     msg_t msg = {0};
     msg.id = id;
     msg.type = type;
     memmove(msg.data, data, size);
     char *str = base64_encode((char *)&msg, sizeof(msg_t));
     zmq_send(c->req_sock, str, strlen(str), 0);
     FREE(str);
     char buff[__MAX_ZMQ_MSG_SIZE] = {0};
     zmq_recv(c->req_sock, buff, __MAX_ZMQ_MSG_SIZE, 0);
     char *decoded = base64_decode(buff);
     msg_t *received = (msg_t *)decoded;
     memmove(out->data, received->data, size);
     ret = received->ret;
     FREE(decoded);
     return ret;
 }
receive_app_events()
static void* receive_app_events (void * null) static
Returns
NULL
Definition at line 135 of file app_event_zmq_pack.h.
References __MAX_ZMQ_MSG_SIZE, av_on, av_pull_sock, base64_decode(), _msg_t::data, flow_av_raise(), FREE, _msg_t::id, log_av_raise(), pktin_av_raise(), pktout_av_raise(), port_av_raise(), and _msg_t::type.
 {
     while (av_on) {
         char buff[__MAX_ZMQ_MSG_SIZE] = {0};
         zmq_recv(av_pull_sock, buff, __MAX_ZMQ_MSG_SIZE, 0);
         if (!av_on) break;
         char *decoded = base64_decode(buff);
         msg_t *msg = (msg_t *)decoded;
         if (msg->id == 0) continue;
         else if (msg->type > AV_NUM_EVENTS) continue;
         switch (msg->type) {
         // upstream events
         case AV_DP_RECEIVE_PACKET:
             pktin_av_raise(msg->id, AV_DP_RECEIVE_PACKET, sizeof(pktin_t), (const pktin_t *)msg->data);
             break;
         case AV_DP_FLOW_EXPIRED:
             flow_av_raise(msg->id, AV_DP_FLOW_EXPIRED, sizeof(flow_t), (const flow_t *)msg->data);
             break;
         case AV_DP_FLOW_DELETED:
             flow_av_raise(msg->id, AV_DP_FLOW_DELETED, sizeof(flow_t), (const flow_t *)msg->data);
             break;
         case AV_DP_PORT_ADDED:
             port_av_raise(msg->id, AV_DP_PORT_ADDED, sizeof(port_t), (const port_t *)msg->data);
             break;
         case AV_DP_PORT_MODIFIED:
             port_av_raise(msg->id, AV_DP_PORT_MODIFIED, sizeof(port_t), (const port_t *)msg->data);
             break;
         case AV_DP_PORT_DELETED:
             port_av_raise(msg->id, AV_DP_PORT_DELETED, sizeof(port_t), (const port_t *)msg->data);
             break;
         // downstream events
         case AV_DP_SEND_PACKET:
             pktout_av_raise(msg->id, AV_DP_SEND_PACKET, sizeof(pktout_t), (const pktout_t *)msg->data);
             break;
         case AV_DP_INSERT_FLOW:
             flow_av_raise(msg->id, AV_DP_INSERT_FLOW, sizeof(flow_t), (const flow_t *)msg->data);
             break;
         case AV_DP_MODIFY_FLOW:
             flow_av_raise(msg->id, AV_DP_MODIFY_FLOW, sizeof(flow_t), (const flow_t *)msg->data);
             break;
         case AV_DP_DELETE_FLOW:
             flow_av_raise(msg->id, AV_DP_DELETE_FLOW, sizeof(flow_t), (const flow_t *)msg->data);
             break;
         // log events
         case AV_LOG_DEBUG:
             log_av_raise(msg->id, AV_LOG_DEBUG, strlen((const char *)msg->data), (const char *)msg->data);
             break;
         case AV_LOG_INFO:
             log_av_raise(msg->id, AV_LOG_INFO, strlen((const char *)msg->data), (const char *)msg->data);
             break;
         case AV_LOG_WARN:
             log_av_raise(msg->id, AV_LOG_WARN, strlen((const char *)msg->data), (const char *)msg->data);
             break;
         case AV_LOG_ERROR:
             log_av_raise(msg->id, AV_LOG_ERROR, strlen((const char *)msg->data), (const char *)msg->data);
             break;
         case AV_LOG_FATAL:
             log_av_raise(msg->id, AV_LOG_FATAL, strlen((const char *)msg->data), (const char *)msg->data);
             break;
         default:
             break;
         }
         FREE(decoded);
     }
     return NULL;
 }
reply_app_events()
static void* reply_app_events (void * null) static
Returns
NULL
Definition at line 79 of file app_event_zmq_pack.h.
 {
     void *recv = zmq_socket(av_rep_ctx, ZMQ_REP);
     zmq_connect(recv, "inproc://av_reply_workers");
     while (av_on) {
         char buff[__MAX_ZMQ_MSG_SIZE] = {0};
         zmq_recv(recv, buff, __MAX_ZMQ_MSG_SIZE, 0);
         if (!av_on) break;
         char *decoded = base64_decode(buff);
         msg_t *msg = (msg_t *)decoded;
         if (msg->id == 0) continue;
         else if (msg->type > AV_NUM_EVENTS) continue;
         switch (msg->type) {
         // request-response events
         default:
             break;
         }
         FREE(decoded);
         char *str = base64_encode((char *)msg, sizeof(msg_t));
         zmq_send(recv, str, strlen(str), 0);
         FREE(str);
         if (!av_on) break;
     }
     zmq_close(recv);
     return NULL;
 }
reply_proxy()
static void* reply_proxy (void * null) static
Returns
NULL
Definition at line 122 of file app_event_zmq_pack.h.
References av_rep_app.
 {
     zmq_proxy(av_rep_app, av_rep_work, NULL);
     return NULL;
 }