Barista: Application Event Handler
Application Event Handler
Base Framework
Functions to manage events for applications.
Files
file app_event.c
static ctx_t * av_ctx
The pointer of the context structure.
static int av_on
The running flag of the application event handler.
void * av_pull_ctx
The MQ contexts to pull events and to handle request-response events.
void * av_rep_ctx
void * av_pull_sock
The MQ socket to pull events.
void * av_rep_app
The MQ sockets for applications and workers.
void * av_rep_work
static int sw_av_raise (uint32_t id, uint16_t type, uint16_t len, const switch_t *data)
Switch related trigger function (non-const)
static int port_av_raise (uint32_t id, uint16_t type, uint16_t len, const port_t *data)
Port related trigger function (const)
static int host_av_raise (uint32_t id, uint16_t type, uint16_t len, const host_t *data)
Host related trigger function (const)
static int pktin_av_raise (uint32_t id, uint16_t type, uint16_t len, const pktin_t *data)
Packet-In related trigger function (const)
static int pktout_av_raise (uint32_t id, uint16_t type, uint16_t len, const pktout_t *data)
Packet-Out related trigger function (const)
static int flow_av_raise (uint32_t id, uint16_t type, uint16_t len, const flow_t *data)
Flow related trigger function (const)
static int log_av_raise (uint32_t id, uint16_t type, uint16_t len, const char *data)
Log related trigger function (const)
void av_dp_receive_packet (uint32_t id, const pktin_t *data)
AV_DP_RECEIVE_PACKET.
void av_dp_flow_expired (uint32_t id, const flow_t *data)
AV_DP_FLOW_EXPIRED.
void av_dp_flow_deleted (uint32_t id, const flow_t *data)
AV_DP_FLOW_DELETED.
void av_dp_port_added (uint32_t id, const port_t *data)
AV_DP_PORT_ADDED.
void av_dp_port_modified (uint32_t id, const port_t *data)
AV_DP_PORT_MODIFIED.
void av_dp_port_deleted (uint32_t id, const port_t *data)
AV_DP_PORT_DELETED.
void av_dp_send_packet (uint32_t id, const pktout_t *data)
AV_DP_SEND_PACKET.
void av_dp_insert_flow (uint32_t id, const flow_t *data)
AV_DP_INSERT_FLOW.
void av_dp_modify_flow (uint32_t id, const flow_t *data)
AV_DP_MODIFY_FLOW.
void av_dp_delete_flow (uint32_t id, const flow_t *data)
AV_DP_DELETE_FLOW.
void av_sw_connected (uint32_t id, const switch_t *data)
AV_SW_CONNECTED.
void av_sw_disconnected (uint32_t id, const switch_t *data)
AV_SW_DISCONNECTED.
void av_host_added (uint32_t id, const host_t *data)
AV_HOST_ADDED.
void av_host_deleted (uint32_t id, const host_t *data)
AV_HOST_DELETED.
void av_link_added (uint32_t id, const port_t *data)
AV_LINK_ADDED.
void av_link_deleted (uint32_t id, const port_t *data)
AV_LINK_DELETED.
void av_flow_added (uint32_t id, const flow_t *data)
AV_FLOW_ADDED.
void av_flow_deleted (uint32_t id, const flow_t *data)
AV_FLOW_DELETED.
void av_log_debug (uint32_t id, char *format,...)
AV_LOG_DEBUG.
void av_log_info (uint32_t id, char *format,...)
AV_LOG_INFO.
void av_log_warn (uint32_t id, char *format,...)
AV_LOG_WARN.
void av_log_error (uint32_t id, char *format,...)
AV_LOG_ERROR.
void av_log_fatal (uint32_t id, char *format,...)
AV_LOG_FATAL.
static void * meta_app_events (void *null)
Function to process meta app events.
int app_event_init (ctx_t *ctx)
Function to initialize the app event handler.
#define ODP_FUNC compare_switch
#define ODP_FUNC compare_port
#define ODP_FUNC compare_host
#define ODP_FUNC compare_pktin
#define ODP_FUNC compare_pktout
#define ODP_FUNC compare_flow
#define ODP_FUNC compare_switch
#define ODP_FUNC compare_port
#define ODP_FUNC compare_host
#define ODP_FUNC compare_pktin
#define ODP_FUNC compare_pktout
#define ODP_FUNC compare_flow
#define ODP_TYPE switch_t
#define ODP_TYPE port_t
#define ODP_TYPE host_t
#define ODP_TYPE pktin_t
#define ODP_TYPE pktout_t
#define ODP_TYPE flow_t
#define FUNC_NAME sw_av_raise
The code of sw_rw_raise()
#define FUNC_NAME port_av_raise
The code of sw_rw_raise()
#define FUNC_NAME host_av_raise
The code of sw_rw_raise()
#define FUNC_NAME pktin_av_raise
The code of sw_rw_raise()
#define FUNC_NAME pktout_av_raise
The code of sw_rw_raise()
#define FUNC_NAME flow_av_raise
The code of sw_rw_raise()
#define FUNC_NAME log_av_raise
The code of sw_rw_raise()
#define FUNC_TYPE switch_t
#define FUNC_TYPE port_t
#define FUNC_TYPE host_t
#define FUNC_TYPE pktin_t
#define FUNC_TYPE pktout_t
#define FUNC_TYPE flow_t
#define FUNC_TYPE char
#define FUNC_DATA sw
#define FUNC_DATA port
#define FUNC_DATA host
#define FUNC_DATA pktin
#define FUNC_DATA pktout
#define FUNC_DATA flow
#define FUNC_DATA log
Detailed Description
Macro Definition Documentation
FUNC_NAME [1/7]
#define FUNC_NAME sw_av_raise
The code of log_av_raise()
The code of flow_av_raise()
The code of pktout_av_raise()
The code of pktin_av_raise()
The code of host_av_raise()
The code of port_av_raise()
Parameters
id Application ID
type App event type
len The length of data
data Data The code of port_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of host_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of flow_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of sw_av_raise()
id Application ID
type App event type
len The length of data
data Data
id Application ID
type App event type
len The length of data
data Data
Definition at line 518 of file app_event.c.
FUNC_NAME [2/7]
#define FUNC_NAME port_av_raise
The code of log_av_raise()
The code of flow_av_raise()
The code of pktout_av_raise()
The code of pktin_av_raise()
The code of host_av_raise()
The code of port_av_raise()
Parameters
id Application ID
type App event type
len The length of data
data Data The code of port_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of host_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of flow_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of sw_av_raise()
id Application ID
type App event type
len The length of data
data Data
id Application ID
type App event type
len The length of data
data Data
Definition at line 518 of file app_event.c.
FUNC_NAME [3/7]
#define FUNC_NAME host_av_raise
The code of log_av_raise()
The code of flow_av_raise()
The code of pktout_av_raise()
The code of pktin_av_raise()
The code of host_av_raise()
The code of port_av_raise()
Parameters
id Application ID
type App event type
len The length of data
data Data The code of port_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of host_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of flow_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of sw_av_raise()
id Application ID
type App event type
len The length of data
data Data
id Application ID
type App event type
len The length of data
data Data
Definition at line 518 of file app_event.c.
FUNC_NAME [4/7]
#define FUNC_NAME pktin_av_raise
The code of log_av_raise()
The code of flow_av_raise()
The code of pktout_av_raise()
The code of pktin_av_raise()
The code of host_av_raise()
The code of port_av_raise()
Parameters
id Application ID
type App event type
len The length of data
data Data The code of port_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of host_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of flow_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of sw_av_raise()
id Application ID
type App event type
len The length of data
data Data
id Application ID
type App event type
len The length of data
data Data
Definition at line 518 of file app_event.c.
FUNC_NAME [5/7]
#define FUNC_NAME pktout_av_raise
The code of log_av_raise()
The code of flow_av_raise()
The code of pktout_av_raise()
The code of pktin_av_raise()
The code of host_av_raise()
The code of port_av_raise()
Parameters
id Application ID
type App event type
len The length of data
data Data The code of port_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of host_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of flow_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of sw_av_raise()
id Application ID
type App event type
len The length of data
data Data
id Application ID
type App event type
len The length of data
data Data
Definition at line 518 of file app_event.c.
FUNC_NAME [6/7]
#define FUNC_NAME flow_av_raise
The code of log_av_raise()
The code of flow_av_raise()
The code of pktout_av_raise()
The code of pktin_av_raise()
The code of host_av_raise()
The code of port_av_raise()
Parameters
id Application ID
type App event type
len The length of data
data Data The code of port_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of host_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of flow_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of sw_av_raise()
id Application ID
type App event type
len The length of data
data Data
id Application ID
type App event type
len The length of data
data Data
Definition at line 518 of file app_event.c.
FUNC_NAME [7/7]
#define FUNC_NAME log_av_raise
The code of log_av_raise()
The code of flow_av_raise()
The code of pktout_av_raise()
The code of pktin_av_raise()
The code of host_av_raise()
The code of port_av_raise()
Parameters
id Application ID
type App event type
len The length of data
data Data The code of port_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of host_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of flow_rw_raise()
id Application ID
type App event type
len The length of data
data Data The code of sw_av_raise()
id Application ID
type App event type
len The length of data
data Data
id Application ID
type App event type
len The length of data
data Data
Definition at line 518 of file app_event.c.
Function Documentation
app_event_init()
int app_event_init (ctx_t * ctx)
Parameters
ctx The context of the Barista NOS
Returns
0: OK, -1: Error
Definition at line 245 of file app_event.c.
Referenced by main().
 {
     av_ctx = ctx;
     if (av_on == FALSE) {
         pthread_t thread;
         if (pthread_create(&thread, NULL, &meta_app_events, NULL) < 0) {
             PERROR("pthread_create");
             return -1;
         }
         av_on = TRUE;
         // pull (outside)
         av_pull_ctx = zmq_ctx_new();
         av_pull_sock = zmq_socket(av_pull_ctx, ZMQ_PULL);
         if (zmq_bind(av_pull_sock, EXT_APP_PULL_ADDR)) {
             PERROR("zmq_bind");
             return -1;
         }
         int i;
         for (i=0; i<__NUM_THREADS; i++) {
             if (pthread_create(&thread, NULL, &receive_app_events, NULL) < 0) {
                 PERROR("pthread_create");
                 return -1;
             }
         }
         // reply
         av_rep_ctx = zmq_ctx_new();
         av_rep_app = zmq_socket(av_rep_ctx, ZMQ_ROUTER);
         if (zmq_bind(av_rep_app, EXT_APP_REPLY_ADDR)) {
             PERROR("zmq_bind");
             return -1;
         }
         av_rep_work = zmq_socket(av_rep_ctx, ZMQ_DEALER);
         if (zmq_bind(av_rep_work, "inproc://av_reply_workers")) {
             PERROR("zmq_bind");
             return -1;
         }
         for (i=0; i<__NUM_THREADS; i++) {
             if (pthread_create(&thread, NULL, &reply_app_events, NULL) < 0) {
                 PERROR("pthread_create");
                 return -1;
             }
         }
         if (pthread_create(&thread, NULL, &reply_proxy, ctx) < 0) {
             PERROR("pthread_create");
             return -1;
         }
     }
     return 0;
 }
meta_app_events()
static void* meta_app_events (void * null) static
Returns
NULL
Definition at line 184 of file app_event.c.
References av_ctx, av_on, _ctx_t::meta_app_event, and _ctx_t::num_app_events.
 {
     int *num_events = av_ctx->num_app_events;
     meta_event_t *meta = av_ctx->meta_app_event;
     while (av_on) {
         int av_id;
         for (av_id=0; av_id<__MAX_APP_EVENTS; av_id++) {
             int num_event = num_events[av_id];
             int j;
             for (j=0; j<__MAX_META_EVENTS; j++) {
                 if (meta[j].event == av_id) {
                     switch (meta[j].condition) {
                     case META_GT: // >
                         if (num_event > meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     case META_GTE: // >=
                         if (num_event >= meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     case META_LT: // <
                         if (num_event < meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     case META_LTE: // <=
                         if (num_event <= meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     case META_EQ: // ==
                         if (num_event == meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     default:
                         break;
                     }
                 }
             }
             num_events[av_id] = 0;
         }
         waitsec(1, 0);
     }
     return NULL;
 }
sw_av_raise()
static int sw_av_raise (uint32_t id, uint16_t type, uint16_t len, const switch_t * data) static
Port related trigger function (non-const) Host related trigger function (non-const) Flow related trigger function (non-const) Switch related trigger function (const)
Referenced by av_sw_connected(), and av_sw_disconnected().