Barista: Packet I/O Engine
Packet I/O Engine
Components
(Base) packet I/O engine
Files
file conn.c
file conn.c
Data Structures
struct of_header
The header of OpenFlow protocol.
struct _context_t
The structure to keep the remaining part of a raw message.
typedef struct _context_t context_t
The structure to keep the remaining part of a raw message.
typedef int(* recv_cb_t) (int sock, uint8_t *rx_buf, int bytes)
The callback definition for network sockets.
int conn_on
The running flag for packet I/O engine.
int queue [1024]
Network socket queue.
int * head
The head and tail pointers of a network socket queue.
int * tail
int size = 0
The number of entries in a network socket queue.
context_t * context
Context buffers for all possible sockets.
int epoll
Epoll for network sockets.
struct epoll_event events [1024]
The event list for network sockets.
recv_cb_t recv_cb = NULL
The callback initialization for network sockets.
pthread_mutex_t queue_mutex
Mutexlock for workers.
pthread_cond_t queue_cond
Condition for workers.
int sc
Network socket.
static void init_queue (void)
Function to initialize a network socket queue.
static void push_back (int v)
Function to push a socket into a network socket queue.
static int pop_front (void)
Function to pop a socket from a network socket queue.
static int get_qsize (void)
Function to get the number of network sockets in a network socket queue.
static void init_context (void)
Function to initialize all context buffers.
static void clean_context (int sock)
Function to clean up a context buffer.
static int msg_proc (int sock, uint8_t *rx_buf, int bytes)
Function to handle incoming messages from network sockets.
static int init_epoll (void)
Function to create an epoll.
static int link_epoll (int epol, int fd, int flags)
Function to add a new socket into an epoll structure.
static int relink_epoll (int epol, int fd, int flags)
Function to add a used socket into an epoll structure.
static void recv_cb_register (recv_cb_t cb)
Function to register a callback function for network sockets.
static void * do_tasks (void *null)
Function to receive raw messages from network sockets.
static void init_workers (void)
Function to initialize network socket workers.
static int nonblocking_mode (const int fd)
Function to set the non-blocking mode to a socket.
static int init_socket (uint16_t port)
Function to initialize a socket.
static void * socket_listen (void *arg)
Function to receive connections from network sockets.
int conn_main (int *activated, int argc, char **argv)
The main function.
int conn_cleanup (int *activated)
The cleanup function.
int conn_cli (cli_t *cli, char **args)
The CLI function.
int conn_handler (const event_t *ev, event_out_t *ev_out)
The handler function.
#define CONN_ID 1651030346
Packet I/O engine ID.
#define MAXQLEN 1024
The size of a network socket queue.
#define FIRST &queue[0]
The pointer of the first entry in a network socket queue.
#define LAST &queue[MAXQLEN - 1]
The pointer of the last entry in a network socket queue.
#define MAXEVENTS 1024
The maximum number of events.
#define BUFFER_SIZE 8192
The size of a recv buffer.
typedef struct _context_t context_t
The structure to keep the remaining part of a raw message.
typedef int(* recv_cb_t) (int sock, uint8_t *rx_buf, int bytes)
The callback definition for network sockets.
int conn_on
The running flag for packet I/O engine.
int queue [1024]
Network socket queue.
int * head
The head and tail pointers of a network socket queue.
int * tail
int size = 0
The number of entries in a network socket queue.
context_t * context
Context buffers for all possible sockets.
int epoll
Epoll for network sockets.
struct epoll_event events [1024]
The event list for network sockets.
recv_cb_t recv_cb = NULL
The callback initialization for network sockets.
pthread_mutex_t queue_mutex
Mutexlock for workers.
pthread_cond_t queue_cond
Condition for workers.
int sc
Network socket.
#define CONN_ID 1651030346
Packet I/O engine ID.
#define MAXQLEN 1024
The size of a network socket queue.
#define FIRST &queue[0]
The pointer of the first entry in a network socket queue.
#define LAST &queue[MAXQLEN - 1]
The pointer of the last entry in a network socket queue.
#define MAXEVENTS 1024
The maximum number of events.
#define BUFFER_SIZE 8192
The size of a recv buffer.
Detailed Description
Function Documentation
clean_context()
static void clean_context (int sock) static
Parameters
sock Network socket
Definition at line 142 of file conn.c.
References context.
 {
     if (context)
         memset(&context[sock], 0, sizeof(context_t));
 }
conn_cleanup()
int conn_cleanup (int * activated)
Parameters
activated The activation flag of this component
Definition at line 641 of file conn.c.
 {
     LOG_INFO(CONN_ID, "Clean up - Packet I/O engine");
     deactivate();
     conn_on = FALSE;
     waitsec(1, 0);
     int i;
     for (i=0; i<__NUM_THREADS; i++) {
         pthread_mutex_lock(&queue_mutex);
         push_back(0);
         pthread_mutex_unlock(&queue_mutex);
         pthread_cond_signal(&queue_cond);
     }
     pthread_cond_destroy(&queue_cond);
     pthread_mutex_destroy(&queue_mutex);
     FREE(context);
     signal(SIGPIPE, SIG_DFL);
     return 0;
 }
conn_cli()
int conn_cli (cli_t * cli, char ** args)
Parameters
cli The CLI pointer
args Arguments
Definition at line 674 of file conn.c.
 {
     return 0;
 }
conn_handler()
int conn_handler (const event_t * ev, event_out_t * ev_out)
Parameters
ev Read-only event
ev_out Read-write event (if this component has the write permission)
Definition at line 684 of file conn.c.
References _event_t::type.
 {
     switch (ev->type) {
     case EV_OFP_MSG_OUT:
         PRINT_EV("EV_OFP_MSG_OUT\n");
         {
             const raw_msg_t *msg = ev->msg;
             int fd = msg->fd;
             int remain = msg->length;
             int bytes = 0;
             int done = 0;
             while (remain > 0) {
                 bytes = write(fd, msg->data + done, remain);
                 if (bytes < 0 && errno != EAGAIN) {
                     break;
                 } else if (bytes < 0) {
                     continue;
                 }
                 remain -= bytes;
                 done += bytes;
             }
         }
         break;
     default:
         break;
     }
     return 0;
 }
conn_main()
int conn_main (int * activated, int argc, char ** argv)
Parameters
activated The activation flag of this component
argc The number of arguments
argv Arguments
Definition at line 615 of file conn.c.
 {
     LOG_INFO(CONN_ID, "Init - Packet I/O engine");
     conn_on = TRUE;
     init_context();
     recv_cb_register(msg_proc);
     init_epoll();
     init_workers();
     init_socket(__DEFAULT_PORT);
     signal(SIGPIPE, SIG_IGN);
     activate();
     socket_listen(NULL);
     return 0;
 }
do_tasks()
static void* do_tasks (void * null) static
Returns
NULL
Definition at line 355 of file conn.c.
References BUFFER_SIZE, conn_on, queue_cond, and queue_mutex.
Referenced by init_workers().
 {
     int wsock, bytes, done = 0;
     uint8_t rx_buf[BUFFER_SIZE] = {0};
     pthread_mutex_lock(&queue_mutex);
     while (conn_on) {
         struct timespec time_wait;
         time_wait.tv_sec = 1;
         time_wait.tv_nsec = 0;
         //pthread_cond_wait(&queue_cond, &queue_mutex);
         pthread_cond_timedwait(&queue_cond, &queue_mutex, &time_wait);
 FETCH_ONE_FD:
         if (conn_on == FALSE) { // clean up
             pthread_mutex_unlock(&queue_mutex);
             break;
         }
         wsock = pop_front();
         if (wsock < 0) continue;
         pthread_mutex_unlock(&queue_mutex);
         done = 0;
         bytes = 1;
         while (bytes > 0) {
             bytes = read(wsock, rx_buf, BUFFER_SIZE);
             if (bytes < 0) {
                 if (errno != EAGAIN) {
                     done = 1;
                 }
                 break;
             } else if (bytes == 0) {
                 done = 1;
                 break;
             }
             bytes = recv_cb(wsock, rx_buf, bytes);
             if (bytes == -1) {
                 done = 1;
                 break;
             }
         }
         if (done) {
             // closed connection
             switch_t sw = {0};
             sw.fd = wsock;
             ev_sw_expired_conn(CONN_ID, &sw);
             clean_context(wsock);
             close(wsock);
         } else {
             if (relink_epoll(epoll, wsock, EPOLLIN | EPOLLET | EPOLLONESHOT) < 0) {
                 // closed connection
                 switch_t sw = {0};
                 sw.fd = wsock;
                 ev_sw_expired_conn(CONN_ID, &sw);
                 clean_context(wsock);
                 close(wsock);
             }
         }
         pthread_mutex_lock(&queue_mutex);
         if (get_qsize() > 0) {
             goto FETCH_ONE_FD;
         }
     }
     return NULL;
 }
get_qsize()
static int get_qsize (void) static
Returns
The number of network sockets in a network socket queue
Definition at line 108 of file conn.c.
References size.
 {
     return size;
 }
init_context()
static void init_context (void) static
Returns
None
Definition at line 129 of file conn.c.
References context.
 {
     context = (context_t *)CALLOC(__DEFAULT_TABLE_SIZE, sizeof(context_t));
     if (context == NULL) {
         PERROR("calloc");
         return;
     }
 }
init_epoll()
static int init_epoll (void) static
Returns
New epoll
Definition at line 274 of file conn.c.
References epoll, events, and MAXEVENTS.
 {
     memset(events, 0, sizeof(struct epoll_event) * MAXEVENTS);
     if ((epoll = epoll_create1(0)) < 0) {
         PERROR("epoll_create1");
         return -1;
     }
     return epoll;
 }
init_queue()
static void init_queue (void) static
Returns
None
Definition at line 63 of file conn.c.
References head, MAXQLEN, and queue.
Referenced by init_workers().
 {
     memset(queue, 0, sizeof(int) * MAXQLEN);
     head = tail = NULL;
     size = 0;
 }
init_socket()
static int init_socket (uint16_t port) static
Parameters
port Port number
Definition at line 486 of file conn.c.
References sc.
 {
     struct sockaddr_in server;
     int option = 1;
     if ((sc = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
         PERROR("socket");
         return -1;
     }
     if (setsockopt(sc, SOL_SOCKET, SO_REUSEADDR, &option, sizeof(option)) < 0) {
         PERROR("setsockopt");
     }
     if (nonblocking_mode(sc) < 0) {
         close(sc);
         return -1;
     }
     server.sin_family = AF_INET;
     server.sin_addr.s_addr = INADDR_ANY;
     server.sin_port = htons(port);
     if (bind(sc, (struct sockaddr *)&server, sizeof(server)) < 0) {
         PERROR("bind");
         close(sc);
         return -1;
     }
     if (listen(sc, SOMAXCONN) < 0) {
         PERROR("listen");
         close(sc);
         return -1;
     }
     if (link_epoll(epoll, sc, EPOLLIN | EPOLLET) < 0) {
         close(sc);
         return -1;
     }
     return sc;
 }
init_workers()
static void init_workers (void) static
Returns
None
Definition at line 435 of file conn.c.
References do_tasks(), init_queue(), queue_cond, and queue_mutex.
 {
     init_queue();
     pthread_mutex_init(&queue_mutex, NULL);
     pthread_cond_init(&queue_cond, NULL);
     int i;
     pthread_t thread;
     for (i=0; i<__NUM_THREADS; i++) {
         if (pthread_create(&thread, NULL, &do_tasks, NULL) < 0) {
             PERROR("pthread_create");
         }
     }
 }
link_epoll()
static int link_epoll (int epol, int fd, int flags) static
Parameters
epol Epoll
fd Socket
flags Epoll flags
Definition at line 292 of file conn.c.
 {
     struct epoll_event event;
     event.data.fd = fd;
     event.events = flags;
     if (epoll_ctl(epol, EPOLL_CTL_ADD, fd, &event) < 0) {
         PERROR("epoll_ctl");
         return -1;
     }
     return 0;
 }
msg_proc()
static int msg_proc (int sock, uint8_t * rx_buf, int bytes) static
Parameters
sock Network socket
rx_buf Input buffer
bytes The size of the input buffer
Definition at line 156 of file conn.c.
References CONN_ID, context, _raw_msg_t::data, _context_t::done, ev_ofp_msg_in(), _raw_msg_t::fd, _raw_msg_t::length, _context_t::need, and _context_t::temp.
 {
     context_t *c = &context[sock];
     uint8_t *temp = c->temp;
     int need = c->need;
     int done = c->done;
     int buf_ptr = 0;
     while (bytes > 0) {
         if (0 < done && done < 4) {
             if (done + bytes < 4) {
                 memmove(temp + done, rx_buf + buf_ptr, bytes);
                 done += bytes;
                 bytes = 0;
                 break;
             } else {
                 memmove(temp + done, rx_buf + buf_ptr, (4 - done));
                 bytes -= (4 - done);
                 buf_ptr += (4 - done);
                 need = ntohs(((struct of_header *)temp)->length) - 4;
                 done = 4;
             }
         }
         if (need == 0) {
             struct of_header *ofph = (struct of_header *)(rx_buf + buf_ptr);
             if (bytes < 4) {
                 memmove(temp, rx_buf + buf_ptr, bytes);
                 need = 0;
                 done = bytes;
                 bytes = 0;
             } else {
                 uint16_t len = ntohs(ofph->length);
                 if (bytes < len) {
                     memmove(temp, rx_buf + buf_ptr, bytes);
                     need = len - bytes;
                     done = bytes;
                     bytes = 0;
                 } else {
                     raw_msg_t msg = {0};
                     msg.fd = sock;
                     msg.length = ntohs(ofph->length);
                     if (msg.length == 0)
                         return -1;
                     memmove(msg.data, rx_buf + buf_ptr, msg.length);
                     ev_ofp_msg_in(CONN_ID, &msg);
                     bytes -= len;
                     buf_ptr += len;
                     need = 0;
                     done = 0;
                 }
             }
         } else {
             struct of_header *ofph = (struct of_header *)temp;
             if (need > bytes) {
                 memmove(temp + done, rx_buf + buf_ptr, bytes);
                 need -= bytes;
                 done += bytes;
                 bytes = 0;
             } else {
                 raw_msg_t msg = {0};
                 msg.fd = sock;
                 msg.length = ntohs(ofph->length);
                 if (msg.length == 0)
                     return -1;
                 memmove(temp + done, rx_buf + buf_ptr, need);
                 memmove(msg.data, temp, msg.length);
                 ev_ofp_msg_in(CONN_ID, &msg);
                 bytes -= need;
                 buf_ptr += need;
                 need = 0;
                 done = 0;
             }
         }
     }
     c->need = need;
     c->done = done;
     return bytes;
 }
nonblocking_mode()
static int nonblocking_mode (const int fd) static
Parameters
fd Socket
Definition at line 460 of file conn.c.
 {
     int flags;
     if ((flags = fcntl(fd, F_GETFL, 0)) < 0) {
         if (errno != EAGAIN) {
             PERROR("fcntl");
             return -1;
         }
     }
     flags |= O_NONBLOCK;
     if (fcntl(fd, F_SETFL, flags) < 0) {
         if (errno != EAGAIN) {
             PERROR("fcntl");
             return -1;
         }
     }
     return 0;
 }
pop_front()
static int pop_front (void) static
Returns
Network socket
Definition at line 91 of file conn.c.
References FIRST, head, LAST, and size.
 {
     int ret = -1;
     if (size > 0) {
         ret = *head;
         head = (LAST - head > 0) ? head + 1 : FIRST;
         size--;
     }
     return ret;
 }
push_back()
static void push_back (int v) static
Parameters
v Network socket
Definition at line 74 of file conn.c.
References head, and size.
 {
     if (size == 0) {
         head = tail = FIRST;
     } else {
         tail = (LAST - tail > 0) ? tail + 1 : FIRST;
     }
     *tail = v;
     size++;
 }
recv_cb_register()
static void recv_cb_register (recv_cb_t cb) static
Parameters
cb The callback function for network sockets
Definition at line 346 of file conn.c.
References recv_cb.
 {
     recv_cb = cb;
 }
relink_epoll()
static int relink_epoll (int epol, int fd, int flags) static
Parameters
epol Epoll
fd Socket
flags Epoll flags
Definition at line 313 of file conn.c.
 {
     struct epoll_event event;
     event.data.fd = fd;
     event.events = flags;
     epoll_ctl(epol, EPOLL_CTL_MOD, fd, &event);
     return 0;
 }
socket_listen()
static void* socket_listen (void * arg) static
Returns
NULL
Definition at line 533 of file conn.c.
References conn_on, epoll, events, and MAXEVENTS.
 {
     int csock;
     int nums = 0;
     struct sockaddr_in client;
     socklen_t len = sizeof(struct sockaddr);
     while (conn_on) {
         nums = epoll_wait(epoll, events, MAXEVENTS, 100);
         if (conn_on == FALSE) break;
         int i;
         for (i=0; i<nums; i++) {
             if (events[i].data.fd == sc) {
                 while (1) {
                     if ((csock = accept(sc, (struct sockaddr *)&client, &len)) < 0) {
                         if (errno != EAGAIN && errno != EWOULDBLOCK) {
                             PERROR("accept");
                         }
                         break;
                     }
                     // clean up the previous segments
                     clean_context(csock);
                     // new connection
                     switch_t sw = {0};
                     sw.fd = csock;
                     ev_sw_new_conn(CONN_ID, &sw);
                     if (nonblocking_mode(csock) < 0) {
                         // closed connection
                         switch_t sw = {0};
                         sw.fd = csock;
                         ev_sw_expired_conn(CONN_ID, &sw);
                         close(csock);
                         break;
                     }
                     if (link_epoll(epoll, csock, EPOLLIN | EPOLLET | EPOLLONESHOT) < 0) {
                         // closed connection
                         switch_t sw = {0};
                         sw.fd = csock;
                         ev_sw_expired_conn(CONN_ID, &sw);
                         close(csock);
                         break;
                     }
                 }
             } else {
                 pthread_mutex_lock(&queue_mutex);
                 push_back(events[i].data.fd);
                 pthread_mutex_unlock(&queue_mutex);
                 pthread_cond_signal(&queue_cond);
             }
         }
         if (nums < 0 && errno != EINTR)
             break;
     }
     if (nums < 0)
         PERROR("epoll_wait");
     close(epoll);
     close(sc);
     LOG_INFO(CONN_ID, "Closed a socket");
     return NULL;
 }