Barista: Hash Function
Hash Function
Utilities
Function to get a hash value using Jenkins hash.
Files
file hash.c
uint32_t hash_func (const uint32_t *data, size_t length)
Function to generate a hash value.
#define rot(x, k) (((x)<<(k)) | ((x)>>(32-(k))))
#define mix(a, b, c)
#define final(a, b, c)
Detailed Description
Macro Definition Documentation
#define final (a, b, c)
Value:
{ \
    c ^= b; c -= rot(b,14); \
    a ^= c; a -= rot(c,11); \
    b ^= a; b -= rot(a,25); \
    c ^= b; c -= rot(b,16); \
    a ^= c; a -= rot(c,4);  \
    b ^= a; b -= rot(a,14); \
    c ^= b; c -= rot(b,24); \
}
Definition at line 35 of file hash.c.
#define mix (a, b, c)
Value:
{ \
    a -= c;  a ^= rot(c, 4);  c += b; \
    b -= a;  b ^= rot(a, 6);  a += c; \
    c -= b;  c ^= rot(b, 8);  b += a; \
    a -= c;  a ^= rot(c,16);  c += b; \
    b -= a;  b ^= rot(a,19);  a += c; \
    c -= b;  c ^= rot(b, 4);  b += a; \
}
Definition at line 25 of file hash.c.
Function Documentation
uint32_t hash_func (const uint32_t * data, size_t length)
Parameters
data Data to make a hash value
length Data length
Returns
Generated hash value
Definition at line 54 of file hash.c.
Referenced by add_new_host(), application_load(), component_load(), config_load(), dit_handler(), host_mgmt_handler(), init_app(), init_compnt(), l2_learning(), l2_shortest(), and load_app_roles().
 {
     uint32_t a,b,c;
     length = length - (length % 4);
     a = b = c = 0xdeadbeef + (((uint32_t)length) << 2);
     while (length > 3) {
         a += data[0];
         b += data[1];
         c += data[2];
         mix(a,b,c);
         length -= 3;
         data += 3;
     }
     switch(length) {
     case 3:
         c += data[2];
     case 2:
         b += data[1];
     case 1:
         a += data[0];
         final(a,b,c);
         break;
     }
     return c;
 }