Barista: Component Event Handler
Component Event Handler
External Component Handler
Functions to manage events for external components.
Files
file event.c
compnt_t compnt
The configuration of an external component.
int ev_worker_on
The running flag for external event workers.
void * ev_push_ctx
MQ contexts to push, pull, request and reply events.
void * ev_pull_in_ctx
void * ev_pull_out_ctx
void * ev_req_ctx
void * ev_rep_ctx
void * ev_pull_in_sock
MQ sockets to pull and reply events.
void * ev_pull_out_sock
void * ev_req_sock
void * ev_rep_comp
void * ev_rep_work
static int handshake (uint32_t id, char *name)
Function to have a handshake with the Barista NOS.
static int ev_push_msg (uint32_t id, uint16_t type, uint16_t size, const void *data)
Function to send events to the Barista NOS.
static int ev_send_msg (uint32_t id, uint16_t type, uint16_t size, const void *input, void *output)
Function to send events to the Barista NOS and receive responses from it.
void ev_ofp_msg_in (uint32_t id, const raw_msg_t *data)
EV_OFP_MSG_IN.
void ev_dp_receive_packet (uint32_t id, const pktin_t *data)
EV_DP_RECEIVE_PACKET.
void ev_dp_flow_expired (uint32_t id, const flow_t *data)
EV_DP_FLOW_EXPIRED.
void ev_dp_flow_deleted (uint32_t id, const flow_t *data)
EV_DP_FLOW_DELETED.
void ev_dp_flow_stats (uint32_t id, const flow_t *data)
EV_DP_FLOW_STATS.
void ev_dp_aggregate_stats (uint32_t id, const flow_t *data)
EV_DP_AGGREGATE_STATS.
void ev_dp_port_added (uint32_t id, const port_t *data)
EV_DP_PORT_ADDED.
void ev_dp_port_modified (uint32_t id, const port_t *data)
EV_DP_PORT_MODIFIED.
void ev_dp_port_deleted (uint32_t id, const port_t *data)
EV_DP_PORT_DELETED.
void ev_dp_port_stats (uint32_t id, const port_t *data)
EV_DP_PORT_STATS.
void ev_ofp_msg_out (uint32_t id, const raw_msg_t *data)
EV_OFP_MSG_OUT.
void ev_dp_send_packet (uint32_t id, const pktout_t *data)
EV_DP_SEND_PACKET.
void ev_dp_insert_flow (uint32_t id, const flow_t *data)
EV_DP_INSERT_FLOW.
void ev_dp_modify_flow (uint32_t id, const flow_t *data)
EV_DP_MODIFY_FLOW.
void ev_dp_delete_flow (uint32_t id, const flow_t *data)
EV_DP_DELETE_FLOW.
void ev_dp_request_flow_stats (uint32_t id, const flow_t *data)
EV_DP_REQUEST_FLOW_STATS.
void ev_dp_request_aggregate_stats (uint32_t id, const flow_t *data)
EV_DP_REQUEST_AGGREGATE_STATS.
void ev_dp_request_port_stats (uint32_t id, const port_t *data)
EV_DP_REQUEST_PORT_STATS.
void ev_sw_get_dpid (uint32_t id, switch_t *data)
EV_SW_GET_DPID (fd)
void ev_sw_get_fd (uint32_t id, switch_t *data)
EV_SW_GET_FD (dpid)
void ev_sw_get_xid (uint32_t id, switch_t *data)
EV_SW_GET_XID (fd or dpid)
void ev_sw_new_conn (uint32_t id, const switch_t *data)
EV_SW_NEW_CONN.
void ev_sw_expired_conn (uint32_t id, const switch_t *data)
EV_SW_EXPIRED_CONN.
void ev_sw_connected (uint32_t id, const switch_t *data)
EV_SW_CONNECTED.
void ev_sw_disconnected (uint32_t id, const switch_t *data)
EV_SW_DISCONNECTED.
void ev_sw_update_config (uint32_t id, const switch_t *data)
EV_SW_UPDATE_CONFIG.
void ev_sw_update_desc (uint32_t id, const switch_t *data)
EV_SW_UPDATE_DESC.
void ev_host_added (uint32_t id, const host_t *data)
EV_HOST_ADDED.
void ev_host_deleted (uint32_t id, const host_t *data)
EV_HOST_DELETED.
void ev_link_added (uint32_t id, const port_t *data)
EV_LINK_ADDED.
void ev_link_deleted (uint32_t id, const port_t *data)
EV_LINK_DELETED.
void ev_flow_added (uint32_t id, const flow_t *data)
EV_FLOW_ADDED.
void ev_flow_deleted (uint32_t id, const flow_t *data)
EV_FLOW_DELETED.
void ev_rs_update_usage (uint32_t id, const resource_t *data)
EV_RS_UPDATE_USAGE.
void ev_tr_update_stats (uint32_t id, const traffic_t *data)
EV_TR_UPDATE_STATS.
void ev_log_update_msgs (uint32_t id, const char *data)
EV_LOG_UPDATE_MSGS.
void ev_log_debug (uint32_t id, char *format,...)
EV_LOG_DEBUG.
void ev_log_info (uint32_t id, char *format,...)
EV_LOG_INFO.
void ev_log_warn (uint32_t id, char *format,...)
EV_LOG_WARN.
void ev_log_error (uint32_t id, char *format,...)
EV_LOG_ERROR.
void ev_log_fatal (uint32_t id, char *format,...)
EV_LOG_FATAL.
static void * reply_events (void *null)
Function to process events in an event queue and reply outputs.
static void * reply_proxy (void *null)
Function to connect worker threads to component threads via a queue proxy.
static void * receive_events (void *null)
Function to receive events from the Barista NOS.
static void * deliver_events (void *null)
Function to get events from an app event queue.
int destroy_ev_workers (ctx_t *null)
Function to destroy an event queue.
int event_init (ctx_t *null)
Function to initialize the event handler.
Detailed Description
Function Documentation
deliver_events()
static void* deliver_events (void * null) static
Parameters
null NULL
Definition at line 541 of file event.c.
References waitsec.
 {
     waitsec(1, 0);
     void *recv = zmq_socket(ev_pull_out_ctx, ZMQ_PULL);
     zmq_connect(recv, "inproc://ev_pull_workers");
     while (ev_worker_on) {
         zmq_msg_t in_msg;
         zmq_msg_init(&in_msg);
         int zmq_ret = zmq_msg_recv(&in_msg, recv, 0);
         if (!ev_worker_on) {
             zmq_msg_close(&in_msg);
             break;
         } else if (zmq_ret == -1) {
             zmq_msg_close(&in_msg);
             continue;
         }
         char *in_str = zmq_msg_data(&in_msg);
         in_str[zmq_ret] = '\0';
         msg_t msg = {0};
         import_from_json(&msg.id, &msg.type, in_str, msg.data);
         zmq_msg_close(&in_msg);
         if (msg.id == 0) continue;
     else if (msg.type > EV_NUM_EVENTS) continue;
         event_out_t out = {0};
         out.id = msg.id;
         out.type = msg.type;
         out.data = msg.data;
         const event_t *in = (const event_t *)&out;
         switch (out.type) {
         // upstream events
         case EV_OFP_MSG_IN:
             out.length = sizeof(raw_msg_t);
             compnt.handler(in, &out);
             break;
         case EV_DP_RECEIVE_PACKET:
             out.length = sizeof(pktin_t);
             compnt.handler(in, &out);
             break;
         case EV_DP_FLOW_EXPIRED:
         case EV_DP_FLOW_DELETED:
         case EV_DP_FLOW_STATS:
         case EV_DP_AGGREGATE_STATS:
             out.length = sizeof(flow_t);
             compnt.handler(in, &out);
             break;
         case EV_DP_PORT_ADDED:
         case EV_DP_PORT_MODIFIED:
         case EV_DP_PORT_DELETED:
         case EV_DP_PORT_STATS:
             out.length = sizeof(port_t);
             compnt.handler(in, &out);
             break;
         // downstream events
         case EV_OFP_MSG_OUT:
             out.length = sizeof(raw_msg_t);
             compnt.handler(in, &out);
             break;
         case EV_DP_SEND_PACKET:
             out.length = sizeof(pktout_t);
             compnt.handler(in, &out);
             break;
         case EV_DP_INSERT_FLOW:
         case EV_DP_MODIFY_FLOW:
         case EV_DP_DELETE_FLOW:
         case EV_DP_REQUEST_FLOW_STATS:
         case EV_DP_REQUEST_AGGREGATE_STATS:
             out.length = sizeof(flow_t);
             compnt.handler(in, &out);
             break;
         case EV_DP_REQUEST_PORT_STATS:
             out.length = sizeof(port_t);
             compnt.handler(in, &out);
             break;
         // internal events (request-response)
         case EV_SW_GET_DPID:
         case EV_SW_GET_FD:
         case EV_SW_GET_XID:
             out.length = sizeof(switch_t);
             compnt.handler(in, &out);
             break;
         // internal events (notification)
         case EV_SW_NEW_CONN:
         case EV_SW_EXPIRED_CONN:
         case EV_SW_CONNECTED:
         case EV_SW_DISCONNECTED:
         case EV_SW_UPDATE_CONFIG:
         case EV_SW_UPDATE_DESC:
             out.length = sizeof(switch_t);
             compnt.handler(in, &out);
             break;
         case EV_HOST_ADDED:
         case EV_HOST_DELETED:
             out.length = sizeof(host_t);
             compnt.handler(in, &out);
             break;
         case EV_LINK_ADDED:
         case EV_LINK_DELETED:
             out.length = sizeof(port_t);
             compnt.handler(in, &out);
             break;
         case EV_FLOW_ADDED:
         case EV_FLOW_MODIFIED:
         case EV_FLOW_DELETED:
             out.length = sizeof(flow_t);
             compnt.handler(in, &out);
             break;
         case EV_RS_UPDATE_USAGE:
             out.length = sizeof(resource_t);
             compnt.handler(in, &out);
             break;
         case EV_TR_UPDATE_STATS:
             out.length = sizeof(traffic_t);
             compnt.handler(in, &out);
             break;
         default:
             break;
         }
     }
     zmq_close(recv);
     return NULL;
 }
destroy_ev_workers()
int destroy_ev_workers (ctx_t * null)
Parameters
null NULL
Definition at line 691 of file event.c.
References ctx, _ctx_t::ev_on, and ev_worker_on.
 {
     ev_worker_on = FALSE;
     waitsec(1, 0);
     zmq_close(ev_pull_in_sock);
     zmq_close(ev_pull_out_sock);
     zmq_close(ev_req_sock);
     zmq_close(ev_rep_comp);
     zmq_close(ev_rep_work);
     //waitsec(1, 0);
     //zmq_ctx_destroy(ev_push_ctx);
     //zmq_ctx_destroy(ev_pull_in_ctx);
     //zmq_ctx_destroy(ev_pull_out_ctx);
     //zmq_ctx_destroy(ev_req_ctx);
     //zmq_ctx_destroy(ev_rep_ctx);
     return 0;
 }
ev_push_msg()
static int ev_push_msg (uint32_t id, uint16_t type, uint16_t size, const void * data) static
Parameters
id Component ID
type Event type
size The size of the given data
data The pointer of the given data
Definition at line 107 of file event.c.
References __MAX_EXT_MSG_SIZE, ev_push_ctx, ev_worker_on, and export_to_json().
Referenced by ev_dp_aggregate_stats(), ev_dp_delete_flow(), ev_dp_flow_deleted(), ev_dp_flow_expired(), ev_dp_flow_stats(), ev_dp_insert_flow(), ev_dp_modify_flow(), ev_dp_port_added(), ev_dp_port_deleted(), ev_dp_port_modified(), ev_dp_port_stats(), ev_dp_receive_packet(), ev_dp_request_aggregate_stats(), ev_dp_request_flow_stats(), ev_dp_request_port_stats(), ev_dp_send_packet(), ev_flow_added(), ev_flow_deleted(), ev_host_added(), ev_host_deleted(), ev_link_added(), ev_link_deleted(), ev_log_update_msgs(), ev_ofp_msg_in(), ev_ofp_msg_out(), ev_rs_update_usage(), ev_sw_connected(), ev_sw_disconnected(), ev_sw_expired_conn(), ev_sw_new_conn(), ev_sw_update_config(), ev_sw_update_desc(), and ev_tr_update_stats().
 {
     if (!ev_worker_on) return -1;
     char out_str[__MAX_EXT_MSG_SIZE];
     export_to_json(id, type, data, out_str);
     zmq_msg_t msg;
     zmq_msg_init_size(&msg, strlen(out_str));
     memcpy(zmq_msg_data(&msg), out_str, strlen(out_str));
     void *sock = zmq_socket(ev_push_ctx, ZMQ_PUSH);
     if (zmq_connect(sock, EXT_COMP_PULL_ADDR)) {
         zmq_msg_close(&msg);
         return -1;
     } else {
         if (zmq_msg_send(&msg, sock, 0) < 0) {
             zmq_close(sock);
             zmq_msg_close(&msg);
             return -1;
         }
         zmq_close(sock);
         zmq_msg_close(&msg);
     }
     return 0;
 }
ev_send_msg()
static int ev_send_msg (uint32_t id, uint16_t type, uint16_t size, const void * input, void * output) static
Parameters
id Component ID
type Event type
size The size of the given data
input The pointer of the given data
output The pointer to store the updated data
Returns
The return value received from the component
Definition at line 145 of file event.c.
References __MAX_EXT_MSG_SIZE, ev_worker_on, and export_to_json().
Referenced by ev_sw_get_dpid(), ev_sw_get_fd(), and ev_sw_get_xid().
 {
     if (!ev_worker_on) return -1;
     char out_str[__MAX_EXT_MSG_SIZE];
     export_to_json(id, type, input, out_str);
     zmq_msg_t msg;
     zmq_msg_init_size(&msg, strlen(out_str));
     memcpy(zmq_msg_data(&msg), out_str, strlen(out_str));
     void *sock = zmq_socket(ev_req_ctx, ZMQ_REQ);
     if (zmq_connect(sock, EXT_COMP_REPLY_ADDR)) {
         zmq_msg_close(&msg);
         return -1;
     } else {
         if (zmq_msg_send(&msg, sock, 0) < 0) {
             zmq_close(sock);
             zmq_msg_close(&msg);
             return -1;
         } else {
             zmq_msg_close(&msg);
             zmq_msg_t in_msg;
             zmq_msg_init(&in_msg);
             int zmq_ret = zmq_msg_recv(&in_msg, sock, 0);
             if (zmq_ret < 0) {
                 zmq_msg_close(&in_msg);
                 zmq_close(sock);
                 return -1;
             } else {
                 char *in_str = zmq_msg_data(&in_msg);
                 in_str[zmq_ret] = '\0';
                 int ret = import_from_json(&id, &type, in_str, output);
                 zmq_close(sock);
                 zmq_msg_close(&in_msg);
                 return ret;
             }
         }
     }
 }
event_init()
int event_init (ctx_t * null)
Parameters
null NULL
Definition at line 718 of file event.c.
References ctx, ev_ctx, _ctx_t::ev_on, ev_pull_in_ctx, ev_pull_in_sock, ev_push_ctx, ev_worker_on, and TRUE.
 {
     ev_worker_on = TRUE;
     // Push (downstream)
     ev_push_ctx = zmq_ctx_new();
     // Pull (upstream, intstream)
     ev_pull_in_ctx = zmq_ctx_new();
     ev_pull_in_sock = zmq_socket(ev_pull_in_ctx, ZMQ_PULL);
     if (zmq_bind(ev_pull_in_sock, TARGET_COMP_PULL_ADDR)) {
         PERROR("zmq_bind");
         return -1;
     }
     ev_pull_out_ctx = zmq_ctx_new();
     ev_pull_out_sock = zmq_socket(ev_pull_out_ctx, ZMQ_PUSH);
     if (zmq_bind(ev_pull_out_sock, "inproc://ev_pull_workers")) {
         PERROR("zmq_bind");
         return -1;
     }
     pthread_t thread;
     if (pthread_create(&thread, NULL, &receive_events, NULL) < 0) {
         PERROR("pthread_create");
         return -1;
     }
     int i;
     for (i=0; i<__NUM_PULL_THREADS; i++) {
         pthread_t thread;
         if (pthread_create(&thread, NULL, &deliver_events, NULL) < 0) {
             PERROR("pthread_create");
             return -1;
         }
     }
     // Request (intsteam)
     ev_req_ctx = zmq_ctx_new();
     // Reply (upstream, intstream)
     ev_rep_ctx = zmq_ctx_new();
     ev_rep_comp = zmq_socket(ev_rep_ctx, ZMQ_ROUTER);
     if (zmq_bind(ev_rep_comp, TARGET_COMP_REPLY_ADDR)) {
         PERROR("zmq_bind");
         return -1;
     }
     ev_rep_work = zmq_socket(ev_rep_ctx, ZMQ_DEALER);
     if (zmq_bind(ev_rep_work, "inproc://ev_reply_workers")) {
         PERROR("zmq_bind");
         return -1;
     }
     for (i=0; i<__NUM_REP_THREADS; i++) {
         pthread_t thread;
         if (pthread_create(&thread, NULL, &reply_events, NULL) < 0) {
             PERROR("pthread_create");
             return -1;
         }
     }
     if (pthread_create(&thread, NULL, &reply_proxy, NULL) < 0) {
         PERROR("pthread_create");
         return -1;
     }
     if (handshake(compnt.component_id, compnt.name))
         return -1;
     return 0;
 }
handshake()
static int handshake (uint32_t id, char * name) static
Parameters
id Component ID
name Component name
Definition at line 49 of file event.c.
 {
     void *sock = zmq_socket(ev_req_ctx, ZMQ_REQ);
     if (zmq_connect(sock, EXT_COMP_REPLY_ADDR)) {
         PERROR("zmq_connect");
         return -1;
     } else {
         char out_str[__MAX_EXT_MSG_SIZE];
         sprintf(out_str, "#{\"id\": %u, \"name\": \"%s\"}", compnt.component_id, compnt.name);
         zmq_msg_t out_msg;
         zmq_msg_init_size(&out_msg, strlen(out_str));
         memcpy(zmq_msg_data(&out_msg), out_str, strlen(out_str));
         if (zmq_send(sock, out_str, strlen(out_str)+1, 0) < 0) {
             PERROR("zmq_send");
             zmq_close(sock);
             zmq_msg_close(&out_msg);
             return -1;
         }
         zmq_msg_close(&out_msg);
         zmq_msg_t in_msg;
         zmq_msg_init(&in_msg);
         int zmq_ret = zmq_msg_recv(&in_msg, sock, 0);
         if (zmq_ret < 0) {
             PERROR("zmq_recv");
             zmq_close(sock);
             zmq_msg_close(&in_msg);
             return -1;
         } else {
             char *in_str = zmq_msg_data(&in_msg);
             in_str[zmq_ret] = '\0';
             if (strcmp(in_str, "#{\"return\": 0}") != 0) {
                 zmq_msg_close(&in_msg);
                 zmq_close(sock);
                 return -1;
             }
         }
         zmq_close(sock);
         zmq_msg_close(&in_msg);
     }
     return 0;
 }
receive_events()
static void* receive_events (void * null) static
Parameters
null NULL
Definition at line 512 of file event.c.
References ev_pull_in_sock, ev_worker_on, and waitsec.
 {
     waitsec(1, 0);
     while (ev_worker_on) {
         zmq_msg_t in_msg;
         zmq_msg_init(&in_msg);
         int zmq_ret = zmq_msg_recv(&in_msg, ev_pull_in_sock, 0);
         if (!ev_worker_on) {
             zmq_msg_close(&in_msg);
             break;
         } else if (zmq_ret == -1) {
             zmq_msg_close(&in_msg);
             continue;
         }
         zmq_msg_send(&in_msg, ev_pull_out_sock, 0);
         zmq_msg_close(&in_msg);
     }
     return NULL;
 }
reply_events()
static void* reply_events (void * null) static
Parameters
null NULL
Definition at line 339 of file event.c.
References waitsec.
 {
     waitsec(1, 0);
     void *recv = zmq_socket(ev_rep_ctx, ZMQ_REP);
     zmq_connect(recv, "inproc://ev_reply_workers");
     while (ev_worker_on) {
         zmq_msg_t in_msg;
         zmq_msg_init(&in_msg);
         int zmq_ret = zmq_msg_recv(&in_msg, recv, 0);
         if (!ev_worker_on) {
             zmq_msg_close(&in_msg);
             break;
         } else if (zmq_ret == -1) {
             zmq_msg_close(&in_msg);
             continue;
         }
         char *in_str = zmq_msg_data(&in_msg);
         in_str[zmq_ret] = '\0';
         msg_t msg = {0};
         import_from_json(&msg.id, &msg.type, in_str, msg.data);
         zmq_msg_close(&in_msg);
         if (msg.id == 0) continue;
     else if (msg.type > EV_NUM_EVENTS) continue;
         event_out_t out = {0};
         out.id = msg.id;
         out.type = msg.type;
         out.data = msg.data;
         const event_t *in = (const event_t *)&out;
         int ret = 0;
         switch (out.type) {
         // upstream events
         case EV_OFP_MSG_IN:
             out.length = sizeof(raw_msg_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_DP_RECEIVE_PACKET:
             out.length = sizeof(pktin_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_DP_FLOW_EXPIRED:
         case EV_DP_FLOW_DELETED:
         case EV_DP_FLOW_STATS:
         case EV_DP_AGGREGATE_STATS:
             out.length = sizeof(flow_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_DP_PORT_ADDED:
         case EV_DP_PORT_MODIFIED:
         case EV_DP_PORT_DELETED:
         case EV_DP_PORT_STATS:
             out.length = sizeof(port_t);
             ret = compnt.handler(in, &out);
             break;
         // downstream events
         case EV_OFP_MSG_OUT:
             out.length = sizeof(raw_msg_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_DP_SEND_PACKET:
             out.length = sizeof(pktout_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_DP_INSERT_FLOW:
         case EV_DP_MODIFY_FLOW:
         case EV_DP_DELETE_FLOW:
         case EV_DP_REQUEST_FLOW_STATS:
         case EV_DP_REQUEST_AGGREGATE_STATS:
             out.length = sizeof(flow_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_DP_REQUEST_PORT_STATS:
             out.length = sizeof(port_t);
             ret = compnt.handler(in, &out);
             break;
         // internal events (request-response)
         case EV_SW_GET_DPID:
         case EV_SW_GET_FD:
         case EV_SW_GET_XID:
             out.length = sizeof(switch_t);
             ret = compnt.handler(in, &out);
             break;
         // internal events (notification)
         case EV_SW_NEW_CONN:
         case EV_SW_EXPIRED_CONN:
         case EV_SW_CONNECTED:
         case EV_SW_DISCONNECTED:
         case EV_SW_UPDATE_CONFIG:
         case EV_SW_UPDATE_DESC:
             out.length = sizeof(switch_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_HOST_ADDED:
         case EV_HOST_DELETED:
             out.length = sizeof(host_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_LINK_ADDED:
         case EV_LINK_DELETED:
             out.length = sizeof(port_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_FLOW_ADDED:
         case EV_FLOW_MODIFIED:
         case EV_FLOW_DELETED:
             out.length = sizeof(flow_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_RS_UPDATE_USAGE:
             out.length = sizeof(resource_t);
             ret = compnt.handler(in, &out);
             break;
         case EV_TR_UPDATE_STATS:
             out.length = sizeof(traffic_t);
             ret = compnt.handler(in, &out);
             break;
         default:
             break;
         }
         msg.ret = ret;
         char out_str[__MAX_EXT_MSG_SIZE];
         export_to_json(msg.id, msg.type, msg.data, out_str);
         zmq_msg_t out_msg;
         zmq_msg_init(&out_msg);
         memcpy(zmq_msg_data(&out_msg), out_str, strlen(out_str));
         zmq_msg_send(&out_msg, recv, 0);
         zmq_msg_close(&out_msg);
         if (!ev_worker_on) break;
     }
     zmq_close(recv);
     return NULL;
 }
reply_proxy()
static void* reply_proxy (void * null) static
Parameters
null NULL
Definition at line 501 of file event.c.
 {
     zmq_proxy(ev_rep_comp, ev_rep_work, NULL);
     return NULL;
 }
Variable Documentation
compnt
compnt_t compnt
The configuration of an external component.
Definition at line 23 of file shim.c.
Referenced by activate_compnt(), deactivate_compnt(), and thread_main().