Barista: Event Handler
Event Handler
Base Framework
Functions to manage events for components.
Files
file event.c
static ctx_t * ev_ctx
The pointer of the context structure.
static int ev_on
The running flag of the event handler.
void * ev_pull_ctx
The MQ context to pull events.
void * ev_pull_sock
The MQ socket to pull events.
void * ev_rep_ctx
The MQ context to handle request-reply events.
void * ev_rep_comp
The MQ sockets for components and workers.
void * ev_rep_work
static int sw_rw_raise (uint32_t id, uint16_t type, uint16_t len, switch_t *data)
Switch related trigger function (non-const)
static int raw_ev_raise (uint32_t id, uint16_t type, uint16_t len, const raw_msg_t *data)
Port related trigger function (non-const)
static int sw_ev_raise (uint32_t id, uint16_t type, uint16_t len, const switch_t *data)
Switch related trigger function (const)
static int port_ev_raise (uint32_t id, uint16_t type, uint16_t len, const port_t *data)
Port related trigger function (const)
static int host_ev_raise (uint32_t id, uint16_t type, uint16_t len, const host_t *data)
Host related trigger function (const)
static int pktin_ev_raise (uint32_t id, uint16_t type, uint16_t len, const pktin_t *data)
Packet-In related trigger function (const)
static int pktout_ev_raise (uint32_t id, uint16_t type, uint16_t len, const pktout_t *data)
Packet-Out related trigger function (const)
static int flow_ev_raise (uint32_t id, uint16_t type, uint16_t len, const flow_t *data)
Flow related trigger function (const)
static int rs_ev_raise (uint32_t id, uint16_t type, uint16_t len, const resource_t *data)
Resource related trigger function (const)
static int tr_ev_raise (uint32_t id, uint16_t type, uint16_t len, const traffic_t *data)
Traffic related trigger function (const)
static int log_ev_raise (uint32_t id, uint16_t type, uint16_t len, const char *data)
Log related trigger function (const)
void ev_ofp_msg_in (uint32_t id, const raw_msg_t *data)
EV_OFP_MSG_IN.
void ev_dp_receive_packet (uint32_t id, const pktin_t *data)
EV_DP_RECEIVE_PACKET.
void ev_dp_flow_expired (uint32_t id, const flow_t *data)
EV_DP_FLOW_EXPIRED.
void ev_dp_flow_deleted (uint32_t id, const flow_t *data)
EV_DP_FLOW_DELETED.
void ev_dp_flow_stats (uint32_t id, const flow_t *data)
EV_DP_FLOW_STATS.
void ev_dp_aggregate_stats (uint32_t id, const flow_t *data)
EV_DP_AGGREGATE_STATS.
void ev_dp_port_added (uint32_t id, const port_t *data)
EV_DP_PORT_ADDED.
void ev_dp_port_modified (uint32_t id, const port_t *data)
EV_DP_PORT_MODIFIED.
void ev_dp_port_deleted (uint32_t id, const port_t *data)
EV_DP_PORT_DELETED.
void ev_dp_port_stats (uint32_t id, const port_t *data)
EV_DP_PORT_STATS.
void ev_ofp_msg_out (uint32_t id, const raw_msg_t *data)
EV_OFP_MSG_OUT.
void ev_dp_send_packet (uint32_t id, const pktout_t *data)
EV_DP_SEND_PACKET.
void ev_dp_insert_flow (uint32_t id, const flow_t *data)
EV_DP_INSERT_FLOW.
void ev_dp_modify_flow (uint32_t id, const flow_t *data)
EV_DP_MODIFY_FLOW.
void ev_dp_delete_flow (uint32_t id, const flow_t *data)
EV_DP_DELETE_FLOW.
void ev_dp_request_flow_stats (uint32_t id, const flow_t *data)
EV_DP_REQUEST_FLOW_STATS.
void ev_dp_request_aggregate_stats (uint32_t id, const flow_t *data)
EV_DP_REQUEST_AGGREGATE_STATS.
void ev_dp_request_port_stats (uint32_t id, const port_t *data)
EV_DP_REQUEST_PORT_STATS.
void ev_sw_get_dpid (uint32_t id, switch_t *data)
EV_SW_GET_DPID (fd)
void ev_sw_get_fd (uint32_t id, switch_t *data)
EV_SW_GET_FD (dpid)
void ev_sw_get_xid (uint32_t id, switch_t *data)
EV_SW_GET_XID (fd or dpid)
void ev_sw_new_conn (uint32_t id, const switch_t *data)
EV_SW_NEW_CONN.
void ev_sw_expired_conn (uint32_t id, const switch_t *data)
EV_SW_EXPIRED_CONN.
void ev_sw_connected (uint32_t id, const switch_t *data)
EV_SW_CONNECTED.
void ev_sw_disconnected (uint32_t id, const switch_t *data)
EV_SW_DISCONNECTED.
void ev_sw_update_config (uint32_t id, const switch_t *data)
EV_SW_UPDATE_CONFIG.
void ev_sw_update_desc (uint32_t id, const switch_t *data)
EV_SW_UPDATE_DESC.
void ev_host_added (uint32_t id, const host_t *data)
EV_HOST_ADDED.
void ev_host_deleted (uint32_t id, const host_t *data)
EV_HOST_DELETED.
void ev_link_added (uint32_t id, const port_t *data)
EV_LINK_ADDED.
void ev_link_deleted (uint32_t id, const port_t *data)
EV_LINK_DELETED.
void ev_flow_added (uint32_t id, const flow_t *data)
EV_FLOW_ADDED.
void ev_flow_modified (uint32_t id, const flow_t *data)
EV_FLOW_MODIFIED.
void ev_flow_deleted (uint32_t id, const flow_t *data)
EV_FLOW_DELETED.
void ev_rs_update_usage (uint32_t id, const resource_t *data)
EV_RS_UPDATE_USAGE.
void ev_tr_update_stats (uint32_t id, const traffic_t *data)
EV_TR_UPDATE_STATS.
void ev_log_update_msgs (uint32_t id, const char *data)
EV_LOG_UPDATE_MSGS.
void ev_log_debug (uint32_t id, char *format,...)
EV_LOG_DEBUG.
void ev_log_info (uint32_t id, char *format,...)
EV_LOG_INFO.
void ev_log_warn (uint32_t id, char *format,...)
EV_LOG_WARN.
void ev_log_error (uint32_t id, char *format,...)
EV_LOG_ERROR.
void ev_log_fatal (uint32_t id, char *format,...)
EV_LOG_FATAL.
static void * meta_events (void *null)
Function to process meta events.
static void * reply_events (void *null)
Function to process requests from components.
static void * reply_proxy (void *null)
Function to connect work threads to component threads via a queue proxy.
static void * receive_events (void *null)
Function to receive events from external components.
int destroy_ev_workers (ctx_t *ctx)
Function to destroy an event queue.
int event_init (ctx_t *ctx)
Function to initialize the event handler.
#define EV_PUSH_EXT_MSG(_id, _type, _size, _data)
#define EV_SEND_EXT_MSG(_id, _type, _size, _data, _output)
#define ODP_FUNC compare_switch
#define ODP_FUNC compare_port
#define ODP_FUNC compare_host
#define ODP_FUNC compare_pktin
#define ODP_FUNC compare_pktout
#define ODP_FUNC compare_flow
#define ODP_FUNC compare_switch
#define ODP_FUNC compare_port
#define ODP_FUNC compare_host
#define ODP_FUNC compare_pktin
#define ODP_FUNC compare_pktout
#define ODP_FUNC compare_flow
#define ODP_TYPE switch_t
#define ODP_TYPE port_t
#define ODP_TYPE host_t
#define ODP_TYPE pktin_t
#define ODP_TYPE pktout_t
#define ODP_TYPE flow_t
#define FUNC_NAME sw_rw_raise
The code of sw_rw_raise()
#define FUNC_NAME raw_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME sw_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME port_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME host_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME pktin_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME pktout_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME flow_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME rs_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME tr_ev_raise
The code of sw_rw_raise()
#define FUNC_NAME log_ev_raise
The code of sw_rw_raise()
#define FUNC_TYPE switch_t
#define FUNC_TYPE raw_msg_t
#define FUNC_TYPE switch_t
#define FUNC_TYPE port_t
#define FUNC_TYPE host_t
#define FUNC_TYPE pktin_t
#define FUNC_TYPE pktout_t
#define FUNC_TYPE flow_t
#define FUNC_TYPE resource_t
#define FUNC_TYPE traffic_t
#define FUNC_TYPE char
#define FUNC_DATA sw_data
#define FUNC_DATA msg
#define FUNC_DATA sw
#define FUNC_DATA port
#define FUNC_DATA host
#define FUNC_DATA pktin
#define FUNC_DATA pktout
#define FUNC_DATA flow
#define FUNC_DATA resource
#define FUNC_DATA traffic
#define FUNC_DATA log
Detailed Description
Macro Definition Documentation
EV_PUSH_EXT_MSG
#define EV_PUSH_EXT_MSG (_id, _type, _size, _data)
Value:
{ \
    msg_t msg = {0}; \
    msg.id = _id; \
    msg.type = _type; \
    memmove(msg.data, _data, _size); \
    if (c->push_sock) { \
        zmq_send(c->push_sock, &msg, sizeof(msg_t), 0); \
    } \
}
Definition at line 82 of file event.c.
EV_SEND_EXT_MSG
#define EV_SEND_EXT_MSG (_id, _type, _size, _data, _output)
Value:
({ \
    msg_t msg = {0}; \
    msg.id = _id; \
    msg.type = _type; \
    memmove(msg.data, _data, _size); \
    if (c->req_sock) { \
        if (zmq_send(c->req_sock, &msg, sizeof(msg_t), 0) != -1) { \
            zmq_recv(c->req_sock, &msg, sizeof(msg_t), 0); \
            memmove(_output->data, msg.data, _size); \
        } else { \
            msg.ret = -1; \
        } \
    } \
    msg.ret; \
})
Definition at line 92 of file event.c.
FUNC_NAME [1/11]
#define FUNC_NAME sw_rw_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [2/11]
#define FUNC_NAME raw_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [3/11]
#define FUNC_NAME sw_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [4/11]
#define FUNC_NAME port_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [5/11]
#define FUNC_NAME host_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [6/11]
#define FUNC_NAME pktin_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [7/11]
#define FUNC_NAME pktout_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [8/11]
#define FUNC_NAME flow_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [9/11]
#define FUNC_NAME rs_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [10/11]
#define FUNC_NAME tr_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
FUNC_NAME [11/11]
#define FUNC_NAME log_ev_raise
The code of log_ev_raise()
The code of tr_ev_raise()
The code of rs_ev_raise()
The code of flow_ev_raise()
The code of pktout_ev_raise()
The code of pktin_ev_raise()
The code of host_ev_raise()
The code of port_ev_raise()
The code of sw_ev_raise()
The code of port_rw_raise()
Parameters
id Component ID
type Event type
len The length of data
data Data
id Component ID
type Event type
len The length of data
data Data The code of host_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of flow_rw_raise()
id Component ID
type Event type
len The length of data
data Data The code of raw_ev_raise()
id Component ID
type Event type
len The length of data
data Data
Definition at line 865 of file event.c.
Function Documentation
destroy_ev_workers()
int destroy_ev_workers (ctx_t * ctx)
Returns
None
Definition at line 524 of file event.c.
Referenced by sigint_handler(), sigkill_handler(), and sigterm_handler().
 {
     ev_on = FALSE;
     waitsec(1, 0);
     zmq_close(ev_pull_sock);
     zmq_ctx_destroy(ev_pull_ctx);
     zmq_close(ev_rep_comp);
     zmq_close(ev_rep_work);
     zmq_ctx_destroy(ev_rep_ctx);
     return 0;
 }
event_init()
int event_init (ctx_t * ctx)
Parameters
ctx The context of the Barista NOS
Definition at line 546 of file event.c.
Referenced by main().
 {
     ev_ctx = ctx;
     if (ev_on == FALSE) {
         pthread_t thread;
         if (pthread_create(&thread, NULL, &meta_events, NULL) < 0) {
             PERROR("pthread_create");
             return -1;
         }
         ev_on = TRUE;
         // pull (outside)
         ev_pull_ctx = zmq_ctx_new();
         ev_pull_sock = zmq_socket(ev_pull_ctx, ZMQ_PULL);
         const int timeout = 1000;
         zmq_setsockopt(ev_pull_sock, ZMQ_RCVTIMEO, &timeout, sizeof(int));
         if (zmq_bind(ev_pull_sock, EXT_COMP_PULL_ADDR)) {
             PERROR("zmq_bind");
             return -1;
         }
         int i;
         for (i=0; i<__NUM_THREADS; i++) {
             if (pthread_create(&thread, NULL, &receive_events, NULL) < 0) {
                 PERROR("pthread_create");
                 return -1;
             }
         }
         // reply
         ev_rep_ctx = zmq_ctx_new();
         ev_rep_comp = zmq_socket(ev_rep_ctx, ZMQ_ROUTER);
         if (zmq_bind(ev_rep_comp, EXT_COMP_REPLY_ADDR)) {
             PERROR("zmq_bind");
             return -1;
         }
         ev_rep_work = zmq_socket(ev_rep_ctx, ZMQ_DEALER);
         if (zmq_bind(ev_rep_work, "inproc://ev_reply_workers")) {
             PERROR("zmq_bind");
             return -1;
         }
         for (i=0; i<__NUM_THREADS; i++) {
             if (pthread_create(&thread, NULL, &reply_events, NULL) < 0) {
                 PERROR("pthread_create");
                 return -1;
             }
         }
         if (pthread_create(&thread, NULL, &reply_proxy, ctx) < 0) {
             PERROR("pthread_create");
             return -1;
         }
     }
     return 0;
 }
meta_events()
static void* meta_events (void * null) static
Returns
NULL
Definition at line 258 of file event.c.
References ev_ctx, _ctx_t::meta_event, and _ctx_t::num_events.
 {
     int *num_events = ev_ctx->num_events;
     meta_event_t *meta = ev_ctx->meta_event;
     while (1) {
         int ev_id;
         for (ev_id=0; ev_id<__MAX_EVENTS; ev_id++) {
             int num_event = num_events[ev_id];
             int j;
             for (j=0; j<__MAX_META_EVENTS; j++) {
                 if (meta[j].event == ev_id) {
                     switch (meta[j].condition) {
                     case META_GT: // >
                         if (num_event > meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     case META_GTE: // >=
                         if (num_event >= meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     case META_LT: // <
                         if (num_event < meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     case META_LTE: // <=
                         if (num_event <= meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     case META_EQ: // ==
                         if (num_event == meta[j].threshold) {
                             //char **args = split_line(meta[j].cmd);
                         }
                         break;
                     default:
                         break;
                     }
                 }
             }
             num_events[ev_id] = 0;
         }
         waitsec(1, 0);
     }
     return NULL;
 }
raw_ev_raise()
static int raw_ev_raise (uint32_t id, uint16_t type, uint16_t len, const raw_msg_t * data) static
Host related trigger function (non-const) Flow related trigger function (non-const) Message related trigger function (const)
Referenced by ev_ofp_msg_in(), ev_ofp_msg_out(), and receive_events().
receive_events()
static void* receive_events (void * null) static
Returns
NULL
Definition at line 374 of file event.c.
References _msg_t::data, ev_on, ev_pull_sock, flow_ev_raise(), host_ev_raise(), _msg_t::id, log_ev_raise(), pktin_ev_raise(), pktout_ev_raise(), port_ev_raise(), raw_ev_raise(), rs_ev_raise(), sw_ev_raise(), tr_ev_raise(), and _msg_t::type.
 {
     while (ev_on) {
         msg_t msg = {0};
         zmq_recv(ev_pull_sock, &msg, sizeof(msg_t), 0);
         if (!ev_on) break;
         else if (msg.id == 0) continue;
         switch (msg.type) {
         // upstream events
         case EV_OFP_MSG_IN:
             raw_ev_raise(msg.id, EV_OFP_MSG_IN, sizeof(raw_msg_t), (const raw_msg_t *)msg.data);
             break;
         case EV_DP_RECEIVE_PACKET:
             pktin_ev_raise(msg.id, EV_DP_RECEIVE_PACKET, sizeof(pktin_t), (const pktin_t *)msg.data);
             break;
         case EV_DP_FLOW_EXPIRED:
             flow_ev_raise(msg.id, EV_DP_FLOW_EXPIRED, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_FLOW_DELETED:
             flow_ev_raise(msg.id, EV_DP_FLOW_DELETED, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_FLOW_STATS:
             flow_ev_raise(msg.id, EV_DP_FLOW_STATS, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_AGGREGATE_STATS:
             flow_ev_raise(msg.id, EV_DP_AGGREGATE_STATS, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_PORT_ADDED:
             port_ev_raise(msg.id, EV_DP_PORT_ADDED, sizeof(port_t), (const port_t *)msg.data);
             break;
         case EV_DP_PORT_MODIFIED:
             port_ev_raise(msg.id, EV_DP_PORT_MODIFIED, sizeof(port_t), (const port_t *)msg.data);
             break;
         case EV_DP_PORT_DELETED:
             port_ev_raise(msg.id, EV_DP_PORT_DELETED, sizeof(port_t), (const port_t *)msg.data);
             break;
         case EV_DP_PORT_STATS:
             port_ev_raise(msg.id, EV_DP_PORT_STATS, sizeof(port_t), (const port_t *)msg.data);
             break;
         // downstream events
         case EV_OFP_MSG_OUT:
             raw_ev_raise(msg.id, EV_OFP_MSG_OUT, sizeof(raw_msg_t), (const raw_msg_t *)msg.data);
             break;
         case EV_DP_SEND_PACKET:
             pktout_ev_raise(msg.id, EV_DP_SEND_PACKET, sizeof(pktout_t), (const pktout_t *)msg.data);
             break;
         case EV_DP_INSERT_FLOW:
             flow_ev_raise(msg.id, EV_DP_INSERT_FLOW, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_MODIFY_FLOW:
             flow_ev_raise(msg.id, EV_DP_MODIFY_FLOW, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_DELETE_FLOW:
             flow_ev_raise(msg.id, EV_DP_DELETE_FLOW, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_REQUEST_FLOW_STATS:
             flow_ev_raise(msg.id, EV_DP_REQUEST_FLOW_STATS, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_REQUEST_AGGREGATE_STATS:
             flow_ev_raise(msg.id, EV_DP_REQUEST_AGGREGATE_STATS, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_DP_REQUEST_PORT_STATS:
             port_ev_raise(msg.id, EV_DP_REQUEST_PORT_STATS, sizeof(port_t), (const port_t *)msg.data);
             break;
         // internal events
         case EV_SW_NEW_CONN:
             sw_ev_raise(msg.id, EV_SW_NEW_CONN, sizeof(switch_t), (const switch_t *)msg.data);
             break;
         case EV_SW_EXPIRED_CONN:
             sw_ev_raise(msg.id, EV_SW_EXPIRED_CONN, sizeof(switch_t), (const switch_t *)msg.data);
             break;
         case EV_SW_CONNECTED:
             sw_ev_raise(msg.id, EV_SW_CONNECTED, sizeof(switch_t), (const switch_t *)msg.data);
             break;
         case EV_SW_DISCONNECTED:
             sw_ev_raise(msg.id, EV_SW_DISCONNECTED, sizeof(switch_t), (const switch_t *)msg.data);
             break;
         case EV_SW_UPDATE_CONFIG:
             sw_ev_raise(msg.id, EV_SW_UPDATE_CONFIG, sizeof(switch_t), (const switch_t *)msg.data);
             break;
         case EV_SW_UPDATE_DESC:
             sw_ev_raise(msg.id, EV_SW_UPDATE_DESC, sizeof(switch_t), (const switch_t *)msg.data);
             break;
         case EV_HOST_ADDED:
             host_ev_raise(msg.id, EV_HOST_ADDED, sizeof(host_t), (const host_t *)msg.data);
             break;
         case EV_HOST_DELETED:
             host_ev_raise(msg.id, EV_HOST_DELETED, sizeof(host_t), (const host_t *)msg.data);
             break;
         case EV_LINK_ADDED:
             port_ev_raise(msg.id, EV_LINK_ADDED, sizeof(port_t), (const port_t *)msg.data);
             break;
         case EV_LINK_DELETED:
             port_ev_raise(msg.id, EV_LINK_DELETED, sizeof(port_t), (const port_t *)msg.data);
             break;
         case EV_FLOW_ADDED:
             flow_ev_raise(msg.id, EV_FLOW_ADDED, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_FLOW_DELETED:
             flow_ev_raise(msg.id, EV_FLOW_DELETED, sizeof(flow_t), (const flow_t *)msg.data);
             break;
         case EV_RS_UPDATE_USAGE:
             rs_ev_raise(msg.id, EV_RS_UPDATE_USAGE, sizeof(resource_t), (const resource_t *)msg.data);
             break;
         case EV_TR_UPDATE_STATS:
             tr_ev_raise(msg.id, EV_TR_UPDATE_STATS, sizeof(traffic_t), (const traffic_t *)msg.data);
             break;
         case EV_LOG_UPDATE_MSGS:
             log_ev_raise(msg.id, EV_LOG_UPDATE_MSGS, strlen((const char *)msg.data), (const char *)msg.data);
             break;
         // log events
         case EV_LOG_DEBUG:
             log_ev_raise(msg.id, EV_LOG_DEBUG, strlen((const char *)msg.data), (const char *)msg.data);
             break;
         case EV_LOG_INFO:
             log_ev_raise(msg.id, EV_LOG_INFO, strlen((const char *)msg.data), (const char *)msg.data);
             break;
         case EV_LOG_WARN:
             log_ev_raise(msg.id, EV_LOG_WARN, strlen((const char *)msg.data), (const char *)msg.data);
             break;
         case EV_LOG_ERROR:
             log_ev_raise(msg.id, EV_LOG_ERROR, strlen((const char *)msg.data), (const char *)msg.data);
             break;
         case EV_LOG_FATAL:
             log_ev_raise(msg.id, EV_LOG_FATAL, strlen((const char *)msg.data), (const char *)msg.data);
             break;
         default:
             break;
         }
     }
     return NULL;
 }
reply_events()
static void* reply_events (void * null) static
Returns
NULL
Definition at line 318 of file event.c.
References _msg_t::data, ev_on, ev_rep_ctx, _msg_t::id, sw_rw_raise(), and _msg_t::type.
 {
     void *recv = zmq_socket(ev_rep_ctx, ZMQ_REP);
     zmq_connect(recv, "inproc://ev_reply_workers");
     while (ev_on) {
         msg_t msg = {0};
         zmq_recv(recv, &msg, sizeof(msg_t), 0);
         if (!ev_on) break;
         else if (msg.id == 0) continue;
         switch (msg.type) {
         // request-response events
         case EV_SW_GET_DPID:
             sw_rw_raise(msg.id, EV_SW_GET_DPID, sizeof(switch_t), (switch_t *)msg.data);
             break;
         case EV_SW_GET_FD:
             sw_rw_raise(msg.id, EV_SW_GET_FD, sizeof(switch_t), (switch_t *)msg.data);
             break;
         case EV_SW_GET_XID:
             sw_rw_raise(msg.id, EV_SW_GET_XID, sizeof(switch_t), (switch_t *)msg.data);
             break;
         default:
             break;
         }
         zmq_send(recv, &msg, sizeof(msg_t), 0);
         if (!ev_on) break;
     }
     zmq_close(recv);
     return NULL;
 }
reply_proxy()
static void* reply_proxy (void * null) static
Returns
NULL
Definition at line 363 of file event.c.
References ev_rep_comp.
 {
     zmq_proxy(ev_rep_comp, ev_rep_work, NULL);
     return NULL;
 }