CREATE DATABASE IF NOT EXISTS barista_mgmt;

USE barista_mgmt;

DROP TABLE IF EXISTS switch_mgmt;
CREATE TABLE switch_mgmt
(
    DPID		BIGINT UNSIGNED NOT NULL,
    MFR_DESC		VARCHAR(256),
    HW_DESC		VARCHAR(256),
    SW_DESC		VARCHAR(256),
    SERIAL_NUM		VARCHAR(32),
    DP_DESC		VARCHAR(256),
    PKT_COUNT		BIGINT UNSIGNED,
    BYTE_COUNT		BIGINT UNSIGNED,
    FLOW_COUNT		INT UNSIGNED,
    UP_TIME             DATETIME DEFAULT CURRENT_TIMESTAMP,
    INSTANCE		VARCHAR(32) NOT NULL,
    PRIMARY KEY(DPID)
);

DROP TABLE IF EXISTS topo_mgmt;
CREATE TABLE topo_mgmt
(
    SRC_DPID            BIGINT UNSIGNED NOT NULL,
    SRC_PORT            INT UNSIGNED NOT NULL,
    DST_DPID            BIGINT UNSIGNED NOT NULL,
    DST_PORT            INT UNSIGNED NOT NULL,
    RX_PACKETS          BIGINT UNSIGNED,
    RX_BYTES            BIGINT UNSIGNED,
    TX_PACKETS          BIGINT UNSIGNED,
    TX_BYTES            BIGINT UNSIGNED,
    INSTANCE            VARCHAR(32) NOT NULL
);

DROP TABLE IF EXISTS host_mgmt;
CREATE TABLE host_mgmt
(
    TIME                DATETIME DEFAULT CURRENT_TIMESTAMP,
    DPID                BIGINT UNSIGNED NOT NULL,
    PORT                INT UNSIGNED NOT NULL,
    IP                  INT UNSIGNED NOT NULL,
    MAC                 BIGINT UNSIGNED NOT NULL,
    INSTANCE            VARCHAR(32) NOT NULL,
    PRIMARY KEY(DPID, MAC)
);

DROP TABLE IF EXISTS flow_mgmt;
CREATE TABLE flow_mgmt
(
    TIME                DATETIME DEFAULT CURRENT_TIMESTAMP,
    DPID                BIGINT UNSIGNED,
    PORT                INT UNSIGNED,
    IDLE_TIMEOUT        INT UNSIGNED NOT NULL,
    HARD_TIMEOUT        INT UNSIGNED NOT NULL,
    WILDCARDS           INT UNSIGNED,
    VLAN_ID             INT UNSIGNED,
    VLAN_PCP            INT UNSIGNED,
    PROTOCOL            INT UNSIGNED,
    IP_TOS              INT UNSIGNED,
    SOURCE_MAC          BIGINT UNSIGNED,
    DESTINATION_MAC     BIGINT UNSIGNED,
    SOURCE_IP           INT UNSIGNED,
    DESTINATION_IP      INT UNSIGNED,
    SOURCE_PORT         SMALLINT UNSIGNED,
    DESTINATION_PORT    SMALLINT UNSIGNED,
    ACTIONS             VARCHAR(256),
    PKT_COUNT           BIGINT UNSIGNED,
    BYTE_COUNT          BIGINT UNSIGNED,
    INSTANCE            VARCHAR(32) NOT NULL
);

DROP TABLE IF EXISTS resource_mgmt;
CREATE TABLE resource_mgmt
(
    ID			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TIME                DATETIME DEFAULT CURRENT_TIMESTAMP,
    CPU                 DOUBLE NOT NULL,
    MEM                 DOUBLE NOT NULL,
    INSTANCE            VARCHAR(32) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS channel_mgmt;
CREATE TABLE channel_mgmt
(
    ID			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TIME                DATETIME DEFAULT CURRENT_TIMESTAMP,
    IN_PKT_CNT          BIGINT UNSIGNED NOT NULL,
    IN_BYTE_CNT         BIGINT UNSIGNED NOT NULL,
    OUT_PKT_CNT         BIGINT UNSIGNED NOT NULL,
    OUT_BYTE_CNT        BIGINT UNSIGNED NOT NULL,
    INSTANCE            VARCHAR(32) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS logs;
CREATE TABLE logs
(
    ID			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TIME		DATETIME DEFAULT CURRENT_TIMESTAMP,
    MESSAGE             VARCHAR(1024) NOT NULL,
    INSTANCE            VARCHAR(32) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS cluster_events;
CREATE TABLE cluster_events
(
    ID			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    EV_ID		INT UNSIGNED NOT NULL,
    EV_TYPE		INT UNSIGNED NOT NULL,
    EV_LENGTH		INT UNSIGNED NOT NULL,
    DATA		VARCHAR(2048) NOT NULL,
    INSTANCE		VARCHAR(32) NOT NULL,
    PRIMARY KEY (ID)
);
