CREATE DATABASE IF NOT EXISTS barista;

USE barista;

DROP TABLE IF EXISTS components;
CREATE TABLE components
(
    COMPNT_ID		INT UNSIGNED NOT NULL,
    COMPNT_NAME		VARCHAR(256) NOT NULL,
    COMPNT_ARGS		VARCHAR(256),
    COMPNT_TYPE		INT NOT NULL,
    COMPNT_SITE		INT NOT NULL,
    COMPNT_ROLE		INT NOT NULL,
    COMPNT_PERM		INT NOT NULL,
    COMPNT_STATUS	INT NOT NULL,
    COMPNT_PRIORITY	INT NOT NULL,
    COMPNT_ACTIVATED	INT NOT NULL,
    UP_TIME		DATETIME,
    DOWN_TIME		DATETIME,
    INSTANCE		VARCHAR(32) NOT NULL,
    PRIMARY KEY(COMPNT_ID)
);

DROP TABLE IF EXISTS applications;
CREATE TABLE applications
(
    APP_ID		INT UNSIGNED NOT NULL,
    APP_NAME		VARCHAR(256) NOT NULL,
    APP_ARGS		VARCHAR(256),
    APP_TYPE		INT NOT NULL,
    APP_SITE		INT NOT NULL,
    APP_ROLE		INT NOT NULL,
    APP_PERM		INT NOT NULL,
    APP_STATUS		INT NOT NULL,
    APP_PRIORITY	INT NOT NULL,
    APP_ACTIVATED	INT NOT NULL,
    UP_TIME		DATETIME,
    DOWN_TIME		DATETIME,
    INSTANCE		VARCHAR(32) NOT NULL,
    PRIMARY KEY(APP_ID)
);

DROP TABLE IF EXISTS events;
CREATE TABLE events
(
    COMPNT_ID		INT NOT NULL,
    EV_ID		INT NOT NULL,
    EV_PERM		INT NOT NULL,
    INSTANCE		VARCHAR(32) NOT NULL
);

DROP TABLE IF EXISTS event_list;
CREATE TABLE event_list
(
    EV_ID		INT NOT NULL,
    EV_NAME		VARCHAR(32) NOT NULL,
    INSTANCE		VARCHAR(32) NOT NULL,
    PRIMARY KEY(EV_ID)
);

DROP TABLE IF EXISTS app_events;
CREATE TABLE app_events
(
    APP_ID		INT NOT NULL,
    AV_ID		INT NOT NULL,
    AV_PERM		INT NOT NULL,
    INSTANCE		VARCHAR(32) NOT NULL
);

DROP TABLE IF EXISTS app_event_list;
CREATE TABLE app_event_list
(
    AV_ID		INT NOT NULL,
    AV_NAME		VARCHAR(32) NOT NULL,
    INSTANCE		VARCHAR(32) NOT NULL,
    PRIMARY KEY(AV_ID)
);

DROP TABLE IF EXISTS operator_defined_policy;
CREATE TABLE operator_defined_policy
(
    ID			INT UNSIGNED NOT NULL,
    DPID		BIGINT UNSIGNED,
    PORT		SMALLINT UNSIGNED,
    PROTOCOL		SMALLINT UNSIGNED,
    VLAN		SMALLINT UNSIGNED,
    SRC_IP		INT UNSIGNED,
    DST_IP		INT UNSIGNED,
    SRC_PORT		SMALLINT UNSIGNED,
    DST_PORT		SMALLINT UNSIGNED,
    INSTANCE		VARCHAR(32) NOT NULL
);
